drools-wb-webapp/pom.xml
This PR is to use configuration to avoid the deployment instead of specifying "none" phase.
The reason behind this is that product tools can handle the configuration and make it from true(=not deploy) to false( =do deploy). The product build env required deployment of every artifacts.
The PR will not chang the "skip" deployment behaviour but it can make sure it can be built in product env.
=> Use configuration to skip deployment

drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-backend/pom.xml, drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-backend/src/main/java/org/drools/workbench/screens/dtablexls/backend/server/DecisionTableXLSServiceImpl.java, drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-backend/src/test/java/org/drools/workbench/screens/dtablexls/backend/server/DecisionTableXLSServiceImplTest.java, drools-wb-screens/drools-wb-scorecard-xls-editor/drools-wb-scorecard-xls-editor-backend/src/main/java/org/drools/workbench/screens/scorecardxls/backend/server/ScoreCardXLSServiceImpl.java
- close input/output streams
- avoid code duplication
- unify exception handling
- add validation when saving xls dt
- and also properly close the Workbook created as a means of validation
- use File instead of InputStream for the Workbook creation as it is supposed to be more memory-friendly, see https://poi.apache.org/apidocs/org/apache/poi/ss/usermodel/WorkbookFactory.html#create(java.io.InputStream)
@manstis something for your experienced eye, I think. ;) It _should_ be okay, but you just never know...
This might also help BZ1332961.
=> cleanup in DecisionTableXLSServiceImpl & ScoreCardXLSServiceImpl

drools-wb-jcr2vfs-migration/drools-wb-jcr2vfs-import/src/test/java/org/drools/workbench/jcr2vfsmigration/WeldTest.java
Backport of #173. Touches just the test.
=> jcr2vfs: properly shutdwon Weld after test finishes

drools-wb-screens/drools-wb-drl-text-editor/drools-wb-drl-text-editor-backend/src/test/java/org/drools/workbench/screens/drltext/backend/server/DRLTextEditorServiceImplTest.java
(part X of moving-tests-to-community series)
=> add test for BZ 1048265 - Creating duplicate DRL silently overwrites.

drools-wb-jcr2vfs-migration/drools-wb-jcr2vfs-export/pom.xml, drools-wb-jcr2vfs-migration/pom.xml
* Guvnor 5.x classes/modules are not fully compatible with
WELD 2.x
=> jcr2vfs: use older WELD 1.x in JCR exporter

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/pom.xml, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerPresenterTest.java
See https://issues.jboss.org/browse/GUVNOR-2538
The Workbench breaks at the moment if you try to open any editor whilst a Guided Decision Table editor is open. The JIRA goes into the gory detail of what's wrong (with Uberfire). This fix is the simplest of the two options!
=> GUVNOR-2538: Guided Decision Table Editor: Fix handling of UpdatedLockStatusEvent

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableEditorPresenter.java
See https://issues.jboss.org/browse/GUVNOR-2541
Simply adds a "Save all" button to the Guided Decision Table editor.
=> GUVNOR-2541: Guided Decision Table Editor: Add support to 'Save all'

drools-wb-webapp/src/main/java/org/drools/workbench/backend/server/AppSetup.java
```drools-wb-webapp``` never used to set System Property ```org.uberfire.watcher.autostart`` to ```false``` however following consolidation of the backend startup logic this System Property is set in ```DefaultApplicationScopedProducer``` and hence ```drools-wb-webapp``` was failing to startup various backend services properly.
=> GUVNOR-2521: Consolidate server-side bootstrap logic in various workbench implementations

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/resources/org/drools/workbench/screens/guided/dtable/client/resources/css/Analysis.css, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-client/src/main/resources/org/drools/workbench/screens/guided/rule/client/resources/css/GuidedRuleEditor.css
Fixes warnings when starting OptaPlanner WB in Super Dev Mode
Computing all possible rebind results for 'org.drools.workbench.screens.guided.dtable.client.resources.GuidedDecisionTableResources'
Rebinding org.drools.workbench.screens.guided.dtable.client.resources.GuidedDecisionTableResources
[WARN] Charset declaration detected. A charset at-rule is not relevant inside a style element
=> PLANNER-579: Reduce WARN messages during startup

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableAttributeSelectorPopup.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableViewImpl.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableAttributeSelectorPopupTest.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-client/src/main/java/org/drools/workbench/screens/guided/rule/client/editor/AttributeSelectorPopup.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-client/src/main/java/org/drools/workbench/screens/guided/rule/client/editor/GuidedRuleAttributeSelectorPopup.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-client/src/main/java/org/drools/workbench/screens/guided/rule/client/editor/RuleAttributeWidget.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-client/src/main/java/org/drools/workbench/screens/guided/rule/client/editor/RuleModeller.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-client/src/main/java/org/drools/workbench/screens/guided/rule/client/resources/images/GuidedRuleEditorImages508.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-client/src/test/java/org/drools/workbench/screens/guided/rule/client/editor/AttributeSelectorPopupTest.java
The original AttributeSelectorPopup code was almost 1:1 copied to GuidedDecisionTableViewImpl. This removes the duplication - the AttributeSelectorPopup is now an abstract parent of 2 separate implementations. Shared code (most logic) stayed there.
This also brings the basic metadata input validation that was present in GRE to GDT.
There are now also a few small tests checking that validation and that duplicates are not allowed (part of moving selenium tests to community).
=> refactor AttributeSelectorPopup code, add some tests

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/auditlog/AuditLogEntryCellHelper.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/auditlog/AuditLogEntryCellHelperTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenter_AuditLogTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/ActionInsertFactColumnSynchronizerTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/ActionRetractFactColumnSynchronizerTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/ActionSetFieldColumnSynchronizerTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/ActionWorkItemColumnSynchronizerTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/ActionWorkItemInsertFactColumnSynchronizerTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/ActionWorkItemSetFieldColumnSynchronizerTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/AttributeColumnSynchronizerTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/BRLActionColumnSynchronizerTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/BRLConditionColumnSynchronizerTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/BaseSynchronizerTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/ConditionColumnSynchronizerTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/MetaDataColumnSynchronizerTest.java
... and clean up AuditLogEntryCellHelper a tiny bit.
This PR relies (a bit) on https://github.com/droolsjbpm/drools/pull/820.
(part n+1 of moving-tests-to-community series)
=> add tests for GDT audit log

drools-wb-jcr2vfs-migration/drools-wb-jcr2vfs-export/pom.xml
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/226
https://github.com/droolsjbpm/drools/pull/815
https://github.com/droolsjbpm/optaplanner/pull/200
https://github.com/droolsjbpm/jbpm/pull/487
https://github.com/droolsjbpm/droolsjbpm-integration/pull/509
https://github.com/droolsjbpm/kie-uberfire-extensions/pull/29
https://github.com/droolsjbpm/guvnor/pull/328
https://github.com/droolsjbpm/drools-wb/pull/209
https://github.com/droolsjbpm/jbpm-designer/pull/302
https://github.com/droolsjbpm/jbpm-console-ng/pull/432
https://github.com/droolsjbpm/kie-wb-distributions/pull/303
=> [DROOLS-1216] exclude commons-logging and use jcl-over-slf4j instead

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/utilities/ColumnUtilitiesTest.java
Operators 'in' & 'not in' should lead to String type column/cell, so that a comma can be used regardless of the field type.
(Part n+1 of 'moving sele tests to community' series.)
=> Add a test for RHBRMS-1841.

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerViewImpl.java
See https://issues.jboss.org/browse/GUVNOR-2604
It should be noted (and I have put similar comment on the JIRA) this is a temporary workaround as all peripheral screens and widgets relating to column definition(s) are to be rewritten as Phase 3 of the editor re-write.
=> GUVNOR-2604: Guided Decision Table Editor: Column definitions DisclosurePanel should scroll if content exceeds available height

drools-wb-webapp/src/main/webapp/WEB-INF/beans.xml
This is required when running the workbench in multi module setup which includes guvnor. Includes additional exclusion for kie-wb-common module.
=> Include guvnor client-side exclusions in beans.xml of drools-wb-webapp module

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/BaseSynchronizer.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/RowSynchronizerTest.java
See https://issues.jboss.org/browse/GUVNOR-2688
The issue was that the old code was calling into ```DTCellValue52( Object o )``` constructor and not ```DTCellValue52( DTCellValue defaultValue )``` constructor.
=> GUVNOR-2688: Guided Decision Tables: Default column values not applied for newly added rows

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/DTCellValueWidgetFactory.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/DefaultValueWidgetFactory.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/columns/dom/datepicker/DatePickerSingletonDOMElementFactory.java
See https://issues.jboss.org/browse/GUVNOR-2689
{{ValueChangeHandler}} is called when the ```DatePicker``` is hidden which led to nested invocation and related error. When the "date" value is changed the ```DatePicker``` container (Panel) is cleared and re-constructed. The clearance led to the ```DatePicker``` being hidden and the {{ValueChangeHandler}} being invoked.. which led to an attempt to clear the panel, hiding the ```DatePicker``` etc. 
Use of ```ChangeDateHandler``` does not suffer the same nested invocation.
=> GUVNOR-2689: Guided Decision Tables: Using DatePickers to set date-effective/date-expired causes controls to disappear

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenterTest.java
See https://issues.jboss.org/browse/GUVNOR-2695
The issue was for enumeration definitions containing a splitter between "real value" (used in DRL) and "display value" (used in the UI) the key for the enumeration definition map was incorrectly the whole enumeration definition; and not just the key component.
=> GUVNOR-2695: Guided Decision Tables: Default column values not applied for newly added rows - part 2

drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-backend/src/main/java/org/drools/workbench/screens/testscenario/backend/server/ScenarioTestEditorServiceImpl.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-backend/src/test/java/org/drools/workbench/screens/testscenario/backend/server/ScenarioTestEditorServiceImplTest.java
See https://issues.jboss.org/browse/GUVNOR-2585
The GUVNOR-2585 was not resolved by the PR https://github.com/droolsjbpm/drools-wb/pull/306 (the fields form the modal were not being imported correctly). This PR imports all the fields correctly.
=> [6.5.x] GUVNOR-2585: In test scenario, expert contraint of type enum can be set but are always false

drools-wb-webapp/pom.xml
@manstis @Rikkola Removing this line from the clean configuration makes SDM startup ~40 seconds faster (once the unitCache is in place):
```Module setup completed in 45802 ms
vs.
Module setup completed in 5721 ms```
@mbarkley and I tested this and we no longer ran into the memory issues, which required the deletion of this directory, that we experienced with earlier versions of GWT 2.8.
Would you guys mind merging this and testing it for a bit in drools-wb before we apply that fix everywhere else?
/cc @porcelli @ederign @psiroky @cristianonicolai
=> Do not delete GWT unitCache during clean

drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/main/java/org/drools/workbench/screens/testscenario/client/ScenarioEditorPresenter.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/test/java/org/drools/workbench/screens/testscenario/client/ScenarioEditorPresenterTest.java
RHBPMS-4388 : [Test Scenario] Scenario have to be run twice to see fired rules
(cherry picked from commit 887cb9e9303b6d8c37b21b3c9d4f72478fd4d9f4)
=> [6.5.x] GUVNOR-2730 : [Test Scenario] Scenario have to be run twice to see fired rules

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/BaseGuidedDecisionTableEditorPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableEditorPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableGraphEditorPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerView.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerViewImpl.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableView.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableViewImpl.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/events/cdi/DecisionTableSelectedEvent.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/BaseGuidedDecisionTableEditorPresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/BaseGuidedDecisionTablePresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableEditorPresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableGraphEditorPresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerPresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenterTest.java
See https://issues.jboss.org/browse/GUVNOR-2735
This PR ensures the "Guided Decision Table Graph Editor" is correctly setup when there are no Decision Tables in the graph. This PR also removes the cumbersome differentiation between "active" and "selected" and ensures the first Decision Table (or singular Decision Table in the "regular" editor) is pre-selected and V&V activated etc.
=> GUVNOR-2735: Guided Decision Table Editor: When opening an empty 'Graph' the editor is not populated

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableGraphEditorPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/handlers/NewGuidedDecisionTableHandler.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/wizard/NewGuidedDecisionTableWizard.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/wizard/NewGuidedDecisionTableWizardHelper.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableGraphEditorPresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/handlers/NewGuidedDecisionTableHandlerTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/wizard/NewGuidedDecisionTableWizardHelperTest.java
See https://issues.jboss.org/browse/GUVNOR-2739
This PR adds the ability to create new Decision Tables whilst editing a graph.
It refactors use of the Decision Table Wizard so it's more easily reusable from both the ```NewGuidedDecisionTableHandler``` and ```GuidedDecisionTableGraphEditorPresenter```.
=> GUVNOR-2739: Guided Decision Table Graph Editor: Add ability to create new Decision Tables from within editor

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenterTest.java
See https://issues.jboss.org/browse/GUVNOR-2740
The issue was "deferred" redraw of the Canvas as opposed to "immediate".
=> GUVNOR-2740: Guided Decision Table Graph Editor: Issue row highlight not working when multiple Editor instances are open

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/CellContextMenu.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/EditMenuBuilder.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/InsertMenuBuilder.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/RadarMenuBuilder.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/RowContextMenu.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/ViewMenuBuilder.java
See https://issues.jboss.org/browse/GUVNOR-2755
Moving to ```@Dependent``` scoped beans not only ensures the menus are correctly re-initialised but also means they work as expected when multiple Editor instances are open. Win, win!
=> GUVNOR-2755: Guided Decision Table Editor: View Menu zoom level does not reset to 100% when re-opening Editor

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/analysis/panel/IssuePresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/analysis/panel/IssuePresenterTest.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-api/src/main/java/org/drools/workbench/services/verifier/api/client/reporting/ExplanationProvider.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-api/src/main/java/org/drools/workbench/services/verifier/api/client/reporting/Issue.java
This PR prevents user from creating `Issue` instances without `ExplnationType`. The only `Issue` without `ExplanationType` is now the static instance `Issue.EMPTY`. As a result of this the `IssuePresenter` was simplified.
=> GUVNOR-2778: Display Issue without ExplanationType

drools-wb-services/drools-wb-verifier/drools-wb-verifier-core/src/main/java/org/drools/workbench/services/verifier/core/cache/RuleInspectorCache.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-core/src/main/java/org/drools/workbench/services/verifier/core/main/Analyzer.java
The method `allRuleInspectors` was identical with the `all` method and thus it is removed. Just wait if the project compiles without errors.
=> GUVNOR-2777: Remove allRuleInspectors method

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/analysis/panel/AnalysisReportScreen.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/analysis/panel/IssuesSet.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/analysis/panel/AnalysisReportScreenTest.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-core/src/main/java/org/drools/workbench/services/verifier/core/checks/DetectEmptyRowCheck.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-web-worker/src/test/java/org/drools/workbench/verifier/webworker/client/DecisionTableAnalyzerTest.java
This PR tries to minimize amount of warnings in Analysis Report panel by collapsing Empty Rule warnings into single line.
=> GUVNOR-2758: Collapse Empty Rules warnings into one line

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/BaseSynchronizer.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/ModelSynchronizerTest.java
See https://issues.jboss.org/browse/GUVNOR-2783
New columns can have the default value for ```boolean``` cells set to ```null```
@karreiro Could you please bare this in mind with the changes you are making for column definition? 
A ```boolean``` column should not really permit ```null``` default values; only ```true``` or ```false``` (unless, or until, we support tri-state ```boolean``` fields, ```null```, ```true``` and ```false``` - but it's unsupported atm).
=> GUVNOR-2783: [Guided Decision Table] Exception thrown during handling Boolean cells

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/AbstractDecisionTableWidget.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/AbstractDecisionTableWidgetTest.java
See https://issues.jboss.org/browse/RHBRMS-2714
This is the corollary of https://github.com/droolsjbpm/drools-wb/pull/358 for 6.5.x
It is however a different implementation as the code-base in this area between 7.x and 6.5.x is different.
=> [6.5.x] RHBRMS-2714: [GSS](6.4.z) GDT editor: existing values get cleared when erasing value from value list

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-api/src/main/java/org/drools/workbench/screens/guided/dtable/service/GuidedDecisionTableEditorService.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/src/main/java/org/drools/workbench/screens/guided/dtable/backend/server/GuidedDecisionTableEditorServiceImpl.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/src/test/java/org/drools/workbench/screens/guided/dtable/backend/server/GuidedDecisionTableEditorServiceImplTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/BaseGuidedDecisionTableEditorPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/BaseGuidedDecisionTableEditorPresenterTest.java
See https://issues.jboss.org/browse/GUVNOR-2784
The issue was that the links in a graph point to versions of the tables; to support opening "old" versions of the graph (that should then show the older versions of the tables). However when updating a single table (not a graph) the links in the graph file still point to the original versions. This PR updates the graphs' links when a single table is saved.
=> GUVNOR-2784: [Guided Decision Table] Changes in individual decision tables doesn't reflect into guided decision table graph

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableGraphEditorPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableGraphEditorPresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenterTest.java
See https://issues.jboss.org/browse/GUVNOR-2814
This PR ensures the "original" ```hashCode``` is correctly set when a graph (or individual table) is loaded. It does however highlight the status of https://issues.jboss.org/browse/GUVNOR-2262 that is related to the JIRA for this PR in that you are no longer prompted when closing a "dirty" guided decision table as the underlying model lacks a ```hashCode``` implementation (other than the default provided by the JVM).
=> GUVNOR-2814: Guided Decision Table Graph: User is always prompted to save or discard data

drools-wb-screens/drools-wb-dsl-text-editor/drools-wb-dsl-text-editor-backend/pom.xml, drools-wb-screens/drools-wb-dsl-text-editor/drools-wb-dsl-text-editor-backend/src/main/java/org/drools/workbench/screens/dsltext/backend/server/DSLInvalidateDMOPackageCacheDeleteHelper.java, drools-wb-screens/drools-wb-enum-editor/drools-wb-enum-editor-backend/pom.xml, drools-wb-screens/drools-wb-enum-editor/drools-wb-enum-editor-backend/src/main/java/org/drools/workbench/screens/enums/backend/server/EnumInvalidateDMOPackageCacheDeleteHelper.java, drools-wb-screens/drools-wb-globals-editor/drools-wb-globals-editor-backend/pom.xml, drools-wb-screens/drools-wb-globals-editor/drools-wb-globals-editor-backend/src/main/java/org/drools/workbench/screens/globals/backend/server/GlobalsInvalidateDMOPackageCacheDeleteHelper.java
See https://issues.jboss.org/browse/GUVNOR-2820
This PR raises events to invalidate the ```LRUDataModelOracleCache``` when certain files are deleted. The cache contains Authoring related meta-data for files in the package; namely DSLs, enumerations and Globals.
=> GUVNOR-2820: Enumerations are present even if they were deleted

drools-wb-jcr2vfs-migration/drools-wb-jcr2vfs-import/pom.xml
We just need the annotaions on classpath so that WELD can load them.
The gwt-user jar is pretty heavyweight (16MiB) and otherwise not needed.
Depends on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/347
=> 	 [DROOLS-1391] no need to depend on gwt-user 

drools-wb-services/drools-wb-verifier/drools-wb-verifier-backend/pom.xml
Removing the generated Errai server marshallers from drools-wb-verifier-backend jar fixes NPEs that several people have experienced after logging into drools-wb in SDM from missing marshaller definitions.
@manstis can you please review this? I'm not exactly sure what drools-wb-verifier-backend does or how to test that it still works.
=> Don't package server marshaller classes in jar.

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/ConditionPopup.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/ConditionPopupView.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/ConditionPopupTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/ConditionPopupViewTest.java
This PR prevents addition of the widget for **Default Value** multiple times. I decided for the simplest solution as this is fix for regression and @karreiro is doing refactoring in this area.
The other possibility I see is to make the method `ConditionPopupView.addDefaultValueIfNoPresent()` private and initialize the **Default Value** widget as part of ConditionPopUp initialization and no as part of `ConditionPopup.makeDefaultValueWidget()`.
=> GUVNOR-2865: Add Default Value widget only once

drools-wb-webapp/src/main/java/org/drools/workbench/client/navbar/AppNavBar.java
This PR ensures the ```LogoNavBar``` is top-most by moving the ```AppNavBar``` down one in order (both had an order of ```Integer.MAX_VALUE``` and hence their runtime order could be indeterminate).
=> Ensure LogoNavBar is top-most

drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-api/src/main/java/org/drools/workbench/screens/testscenario/model/TestScenarioResult.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-backend/src/main/java/org/drools/workbench/screens/testscenario/backend/server/ScenarioRunnerService.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-backend/src/test/java/org/drools/workbench/screens/testscenario/backend/server/ScenarioRunnerServiceTest.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/test/java/org/drools/workbench/screens/testscenario/client/ScenarioEditorPresenterTest.java
The biggest issue with the User field was that it was @RequestScoped.
The ScenarioRunnerService is being used as part of AsyncJobs (e.g.
when the project/maven/test REST endpoint is triggered). On Tomcat
this does not work, becuase the request thread is different from the
processing thread and thus the request scoped variables are not
available. For some reason this works on WildFly 10 / EAP7
(most likely because we use the async EJBs there, instead of the
thred pool).
@Rikkola could you please review?
=> [GUVNOR-2880] remove unused field causing issues on Tomcat

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/ActionInsertFactPopup.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/ActionSetFieldPopup.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/ConditionPopup.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/ConditionPopupView.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/ActionInsertFactPopupTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/ActionSetFieldPopupTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/ConditionPopupTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/ConditionPopupViewTest.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-client/src/main/java/org/drools/workbench/screens/guided/rule/client/editor/AttributeSelectorPopup.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-client/src/test/java/org/drools/workbench/screens/guided/rule/client/editor/AttributeSelectorPopupTest.java
ConditionPopupTest, ConditionPopupViewTest, ActionInsertFactPopupTest, ActionSetFieldPopupTest and AtributeSelectorPopupTest (and corresponding classes) have been refactored to not fail with the new jacoco setup in https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/381.
=> refactor stubbed tests to not fail with offline jacoco instrumentation

drools-wb-jcr2vfs-migration/drools-wb-jcr2vfs-export/pom.xml
Depends on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/405
=> Fix bouncycastle exclusions after itext upgrade

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/PrioritySynchronizer.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/BaseSynchronizerTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/SystemControlledColumnValuesSynchronizerTest.java
This PR increases coverage of moving rows with set PriorityOver and also
fixes two small issues.
The first issue was, that when te row with PriorityOver Row X was moved
to the position X, his PriorityOver wasn't cleared. It means that the
Row X with PriorityOver X was in the table.
The second fixed issue. When there were Rows: 1, 2, 3 with Priorities
None, 1, 1 and the Row 1 was moved to Row 3 then the priorites were None,
3, None. Now the priorities will be None, None, None as expected.
=> GUVNOR-2854: Increase coverage for moving rows with PriorityOver

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/handlers/NewGuidedDecisionTableHandler.java
GUVNOR-2952: [Library] Breadcrumb should be updated when the opened project is renamed
GUVNOR-2947: [Library] Fix create new asset dropdown overflow and order items alphabetically
GUVNOR-2946: [Library] Show business process, guided decision table, data object first at the empty project screen (and order the rest alphabetically).
GUVNOR-2951: [Library] Add option to create new folder/package in a project.
=> Library issues fix

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableGraphEditorPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableGraphEditorPresenterTest.java
See https://issues.jboss.org/browse/GUVNOR-2976
This PR changes the "can save" mechanism to only check "Overview" content for the Graph itself and not for each Decision Table document too. The "Overview" tab shows that for the whole Graph and does not change when individual tables are selected.
=> GUVNOR-2976: Guided Decision Table Graph: Save operation saves changes just to selected graph

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/plugins/ActionSetFactPlugin.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/plugins/ActionSetFactPluginTest.java
See https://issues.jboss.org/browse/GUVNOR-2998
- Before:
- After:
=> GUVNOR-2998: GDT Editor - New column (wizard) - Error on 'Set the value of a field' plugin

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/BaseGuidedDecisionTablePresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenterTest.java
See https://issues.jboss.org/browse/GUVNOR-3013
The link was being created in the wrong "direction"; so link from A1.setLink(C1) was overwritten when we linked A1.setLink(C2). This PR fixes with C1.setLink(A1) and C2.setLink(A1). The UI was therefore only showing the "latest" link giving the impression the BRL-table was unlinked.
=> GUVNOR-3013: Guided Decision Table Graph: BRL fragments are not linked

drools-wb-screens/drools-wb-dsl-text-editor/drools-wb-dsl-text-editor-backend/src/main/java/org/drools/workbench/screens/dsltext/backend/server/indexing/DslFileIndexer.java, drools-wb-screens/drools-wb-dsl-text-editor/drools-wb-dsl-text-editor-backend/src/test/java/org/drools/workbench/screens/dsltext/backend/server/indexing/IndexDefaultPackageDslEntriesTest.java, drools-wb-screens/drools-wb-dsl-text-editor/drools-wb-dsl-text-editor-backend/src/test/java/org/drools/workbench/screens/dsltext/backend/server/indexing/IndexDslInvalidDrlTest.java, drools-wb-screens/drools-wb-dsl-text-editor/drools-wb-dsl-text-editor-backend/src/test/java/org/drools/workbench/screens/dsltext/backend/server/indexing/TestDslFileIndexer.java
See https://issues.jboss.org/browse/GUVNOR-3037
The issue was that when the file was in the default package; the package name is an empty ```String``` and the ```DRL``` generated from the ```DSL``` (to extract class and field references etc) was of the form ```package rule "test" when... ``` and failed ```DRL``` compilation. The resulting error was logged as a warning (but not listed with the default log level).
=> GUVNOR-3037: Lucene Index: DSL files that are created into default package should be indexed

drools-wb-webapp/pom.xml, pom.xml
This is the corollary of https://github.com/kiegroup/drools-wb/pull/471 for 7.0.x
(cherry picked from commit 24e27dcb05ed504e7503c103d5b2f5565eae0535)
=> [7.0.x] Fix Dash Builder dependencies

drools-wb-screens/drools-wb-dsl-text-editor/drools-wb-dsl-text-editor-backend/src/main/java/org/drools/workbench/screens/dsltext/backend/server/indexing/DslFileIndexer.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-backend/src/main/java/org/drools/workbench/screens/testscenario/backend/server/indexing/TestScenarioFileIndexer.java
This is the corollary of https://github.com/kiegroup/drools-wb/pull/465 for 7.0.x
(cherry picked from commit 7ac22656f128ecc121eebea9bffa846f8aca463b)
=> [7.0.x] GUVNOR-2787: [Library] Use Lucene to list assets in the project page

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/plugins/ActionSetFactPlugin.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/plugins/ActionSetFactPluginTest.java
See https://issues.jboss.org/browse/GUVNOR-2998
This is the corollary of https://github.com/kiegroup/drools-wb/pull/453 for 7.0.x
(cherry picked from commit e8d6a3186c2ab707dcdb19df4444505a1eb3ffb3)
=> [7.0.x] GUVNOR-2998: GDT Editor - New column (wizard) - Error on 'Set the value of a field' plugin

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/src/main/java/org/drools/workbench/screens/guided/dtable/backend/server/indexing/GuidedDecisionTableGraphFileIndexer.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/src/main/java/org/drools/workbench/screens/guided/dtable/backend/server/indexing/GuidedDecisionTableGraphModelIndexVisitor.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/src/test/java/org/drools/workbench/screens/guided/dtable/backend/server/indexing/IndexGuidedDecisionTableGraphFileTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/src/test/java/org/drools/workbench/screens/guided/dtable/backend/server/indexing/TestGuidedDecisionTableGraphFileIndexer.java
See https://issues.jboss.org/browse/GUVNOR-3050
This is the corollary of https://github.com/kiegroup/drools-wb/pull/480 for 7.0.x
(cherry picked from commit 1cc3f4591804907067900a61405589bde4a993f5)
=> [7.0.x] GUVNOR-3050: Guided Decision Table Graph: Missing Indexer

drools-wb-services/drools-wb-verifier/drools-wb-verifier-api/pom.xml, drools-wb-services/drools-wb-verifier/drools-wb-verifier-api/src/main/java/org/drools/workbench/services/verifier/api/client/reporting/ImpossibleMatchIssue.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-api/src/main/java/org/drools/workbench/services/verifier/api/client/reporting/MultipleValuesForOneActionIssue.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-api/src/main/resources/ErraiApp.properties, drools-wb-services/drools-wb-verifier/drools-wb-verifier-api/src/test/java/org/drools/workbench/services/verifier/api/client/MarshallingTest.java
https://issues.jboss.org/browse/GUVNOR-2782
@jomarko Hey, this was my take on the fix for #442, but while this picks up several of the bugs that I ran into previously it does not pick up of fix the bug you found. Still a good addition to our test coverage and this can be extended from this simple hashcode comparison.
To really test the actual cause we would have to compile to GWT. I tried with GWT Test Case. It is slow and hard to setup. I think a better bet is to make a selenium test since:
a. We already test with Selenium
b. No need to compile any code to JavaScript
Made a ticket for it. https://issues.jboss.org/browse/GUVNOR-3071
=> GUVNOR-2782 : [Guided Decision Table] Row with Impossible Match throws Exception

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableGraphEditorPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableGraphEditorPresenterTest.java
The save operation on graph that doesn't inlcude decision tables was causing never
ending saving. In practise, the saving progress popup was never hidden.
@manstis please take a look when you have a while. I forgot to check this yesterday. Sorry for inconvenience.
=> GUVNOR-3078: Save of empty graph never ends

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableEditorPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableEditorPresenterTest.java
See https://issues.jboss.org/browse/GUVNOR-3092
@jomarko This was caused by https://issues.jboss.org/browse/GUVNOR-3078
The old code used to close the editor when the last document was deregistered (which for a "graph" was undesirable; but for the single decision table editor deletion of the file deregistered the document which no longer lead to closure).
=> GUVNOR-3092: [Guided Decision Table Graph] Editor does not close when deleting file

drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/main/java/org/drools/workbench/screens/testscenario/client/ScenarioWidgetComponentCreator.java
See https://issues.jboss.org/browse/GUVNOR-3134
This PR effectively reverts https://github.com/kiegroup/droolswb/commit/a12cd9b352322df1e9ea75b93ce455f95192a8a5 made for https://issues.jboss.org/browse/GUVNOR-2980 that attempted to switch to use of 'Fully Qualified Rule Names' for Test Scenarios. However this causes problems with backwards compatibility and an alternative solution has been added for GUVNOR-3134 keeping use of 'Simple Rule Names'.
=> GUVNOR-3134: Test scenarios fail after upgrade to 7.1 because rule expectation in 6.x doesn't use FQN

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerViewImpl.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableViewImpl.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/keyboard/KeyDownHandlerCommon.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerViewImplTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/keyboard/KeyDownHandlerCommonTest.java
See https://issues.jboss.org/browse/GUVNOR-3146
@jomarko I've tested with Chrome and FF and keyboard navigation still works OK (remember the "tab" issue on FF, when ```Shift```-tabbing out of ```TextBox``` would "disable" keyboard interaction?  
I also took the liberty of fixing a small rendering [issue](https://github.com/kiegroup/drools-wb/pull/526/files#diff-e380c5924f6e5d1bd9b7ee1800b10de4R154) evident in "graphs" when it's possible to see a de-selected table. The ```IPathClipper``` was clipping the right border from the header.
=> GUVNOR-3146: Attach Modeller's KeyDownHandler to editor not RootPanel

drools-wb-webapp/pom.xml, drools-wb-webapp/src/main/resources/org/drools/workbench/DroolsWorkbench.gwt.xml
Add the required dependencies so as to make the project dashboard metrics work in showcase.
@paulovmr I did run it locally without issues. Can you verify please?
=> JBPM-5876: Fix runtime dependencies

drools-wb-webapp/pom.xml, drools-wb-webapp/src/main/resources/log4j.xml, drools-wb-webapp/src/main/resources/logback.xml, drools-wb-webapp/src/main/resources/org/drools/workbench/DroolsWorkbench.gwt.xml
Based on this PR: https://github.com/AppFormer/uberfire/pull/718
It change some ApplicationScoped beans to be WorkspaceScoped, check referenced PR
=> [UF-506] WorkspaceScoped Services

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/RadarMenuBuilder.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerView.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerViewImpl.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/RadarMenuBuilderTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerPresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerViewImplTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenterTest.java
Cherry picked from https://github.com/kiegroup/drools-wb/pull/583
---
- https://github.com/kiegroup/drools-wb/pull/594
- https://github.com/AppFormer/uberfire/pull/819
---
PS: We don't need to update `kie-wb-common` on `7.3.x`.
=> [7.3.x] GUVNOR-3198: [Guided Decision Table] Visual indication where the current view of Decision Table is located

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-api/src/main/java/org/drools/workbench/screens/guided/dtable/shared/DefaultGuidedDecisionTableLinkManager.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-api/src/test/java/org/drools/workbench/screens/guided/dtable/shared/DefaultGuidedDecisionTableLinkManagerTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenterTest.java
See https://issues.jboss.org/browse/GUVNOR-3472
@jomarko This PR also fixes an existing "linking" test.
Test ```fieldConstraintWithActionBRLFragmentFieldWithoutTemplateKey()``` never formed a link and hence the ascertain never executed and never failed. The reason was that ```BRLActionColumn``` with no Template Keys (and hence a boolean column) should have links checked against the definition itself.
=> GUVNOR-3472: [Guided Decision Table] GDT Graph creation causes Error Popup

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerViewImpl.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerViewImplTest.java
See https://issues.jboss.org/browse/GUVNOR-3491
This is the corollary of https://github.com/kiegroup/drools-wb/pull/608 for 7.3.x
(cherry picked from commit 862bb2606f025b66d4a19d90c023ed4e098acbe6)
=> [7.3.x] GUVNOR-3491: [Guided Decision Table] Context menu doesn't disappear if editor toolbar is clicked and even if the editor is closed

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/BaseGuidedDecisionTableEditorPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerViewImpl.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/BaseGuidedDecisionTableEditorPresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerPresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerViewImplTest.java
See https://issues.jboss.org/browse/GUVNOR-3486
@jomarko @karreiro I noticed, with a "graph", that selection of a table (clicking on it) resets the scrollbar position to the origin (0,0).. I double checked this is not caused by this PR. If either of you confirm then I'll open a new JIRA (for @karreiro sorry) as selection of a table should not affect the canvas scroll.
=> GUVNOR-3486: [Guided Decision Table Graph] Refresh after removal of table

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/BaseGuidedDecisionTableEditorPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerViewImpl.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/BaseGuidedDecisionTableEditorPresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerPresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerViewImplTest.java
See https://issues.jboss.org/browse/GUVNOR-3486
This is the corollary of https://github.com/kiegroup/drools-wb/pull/604 for 7.3.x
(cherry picked from commit ef437d5ca1ccccc02cc17df377d235a37dda1c4b)
=> [7.3.x] GUVNOR-3486: [Guided Decision Table Graph] Refresh after removal of table

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/wizard/table/pages/FactPatternConstraintsPageTest.java
https://issues.jboss.org/browse/GUVNOR-3479
(cherry picked from commit bee14c31269815023e20a29b4edd65649afe5aa6)
https://github.com/kiegroup/drools/pull/1480
https://github.com/kiegroup/kie-wb-common/pull/1173
https://github.com/kiegroup/drools-wb/pull/626
=> [7.3.x] GUVNOR-3479 : [GSS-RFE] Add support for missing keywords like "not matches" condition in Guided Rule

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableView.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/commons/HasPatternPage.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/pages/PatternPage.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/plugins/ActionSetFactPlugin.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/plugins/ActionWorkItemSetFieldPlugin.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/plugins/ConditionColumnPlugin.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/plugins/commons/PatternWrapper.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/pages/PatternPageTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/plugins/ActionSetFactPluginTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/plugins/ActionWorkItemSetFieldPluginTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/plugins/ConditionColumnPluginTest.java
See https://issues.jboss.org/browse/GUVNOR-3547
Corollary of https://github.com/kiegroup/drools-wb/pull/648 for 7.4.x
(Product https://issues.jboss.org/browse/RHBRMS-2905 is approved blocker for 7.0.0.LA)
(cherry picked from commit 34d410814fa67f5a644ce468dac8710c7e14f11b)
=> [7.4.x] GUVNOR-3547: [Guided Decision Table] Patterns from BRL conditions are not available for another action columns

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/EditMenuBuilder.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/NewGuidedDecisionTableColumnWizard.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/pages/AdditionalInfoPageView.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/pages/PatternPageView.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/pages/ValueOptionsPageView.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/pages/common/DecisionTableColumnViewUtils.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/pages/common/DecisionTablePopoverUtils.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableEditorMenusTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/EditMenuBuilderTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/PluginHandlerTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/NewGuidedDecisionTableColumnWizardTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/pages/common/DecisionTablePopoverUtilsTest.java
See https://issues.jboss.org/browse/GUVNOR-3556
This is the corollary of https://github.com/kiegroup/drools-wb/pull/651 for 7.4.x
(cherry picked from commit 3bb679d1cbf5091644d4d8f0952476bbc9dbfe65)
(Product JIRA https://issues.jboss.org/browse/RHBRMS-3001 is an approved blocker for 7.0.0.LA)
=> [7.4.x] GUVNOR-3556: [Guided Decision Table] Default Value hint stays shown after wizard is finished or cancelled

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerView.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerViewImpl.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/AccessTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerPresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenterTest.java
Opening a table was setting column manipulation buttons state just for the Add Column button. As there is probably not case, when Add Collumn button could be enabled and Edit Column button disabled (and vice versa), the Table Modeller view API was simplified by removing method that is setting state just for Add Column button.
=> GUVNOR-3578: Disable or Enable both column manipulation buttons

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/BRLConditionColumnSynchronizer.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/BRLConditionColumnSynchronizerTest.java
See https://issues.jboss.org/browse/DROOLS-2074
@jomarko The issue was that an "update" to a BRL Condition is effectively an "add" (of the updated) definition and then a "delete" (of the old). The veto exception was caused because the "delete" checks if any bindings in the fragment being deleted are used in the RHS (or other LHS elements). I've simply skipped the "delete" check when invoked as part of the update. 
This is safe as the "update" first checks if any deleted bindings (difference between original bindings and updated bindings) are used in the RHS (or other LHS elements) and fails fast if any are found.
=> DROOLS-2074: [Guided Decision Table] BRL Condition Update is Vetoed

drools-wb-webapp/pom.xml
Please see this [PR](https://github.com/kiegroup/kie-soup/pull/8) for general discussion.
=> AF-593+: Move uberfire-maven-utils to kie-soup.

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/pages/RuleModellerPageTest.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-backend/src/test/java/org/drools/workbench/screens/guided/rule/backend/server/GuidedRuleEditorServiceImplTest.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-client/pom.xml, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-client/src/main/java/org/drools/workbench/screens/guided/rule/client/editor/AbstractRuleModellerSelectorPopup.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-client/src/main/java/org/drools/workbench/screens/guided/rule/client/editor/GuidedRuleEditorPresenter.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-client/src/main/java/org/drools/workbench/screens/guided/rule/client/editor/RuleModellerConditionSelectorPopup.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-client/src/test/java/org/drools/workbench/screens/guided/rule/client/editor/GuidedRuleEditorPresenterTest.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-client/src/test/java/org/drools/workbench/screens/guided/rule/client/editor/RuleModellerConditionSelectorPopupTest.java, drools-wb-screens/drools-wb-guided-template-editor/drools-wb-guided-template-editor-client/pom.xml, drools-wb-screens/drools-wb-guided-template-editor/drools-wb-guided-template-editor-client/src/main/java/org/drools/workbench/screens/guided/template/client/editor/GuidedRuleTemplateEditorPresenter.java, drools-wb-screens/drools-wb-guided-template-editor/drools-wb-guided-template-editor-client/src/test/java/org/drools/workbench/screens/guided/template/client/editor/GuidedRuleTemplateEditorPresenterTest.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/pom.xml
This PR adds reproducer test that assert DSL sentences are loaded
correctly into given popups:
- Colum Wizard in Guided decision table editor
- Guided Rule editor
- Guided Rule Template editor
@manstis I would like to ask you for review.
=> DROOLS-2076: Add reproducer test for the guided rule editor

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/pom.xml
Fixing the following warning
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.drools:drools-wb-guided-dtable-editor-backend:jar:7.5.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.kie.soup:kie-soup-project-datamodel-api:jar -> duplicate declaration of version (?) @ org.drools:drools-wb-guided-dtable-editor-backend:[unknown-version], /home/hrk/Devel/github.com/kiegroup/drools-wb/drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/pom.xml, line 28, column 17
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer …
```
=> Remove duplicated dependencies

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/BaseMenu.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/BaseMenuView.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/CellContextMenu.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/EditMenuBuilder.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/InsertMenuBuilder.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/RowContextMenu.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/ViewMenuBuilder.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/events/cdi/RefreshMenusEvent.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/CellContextMenuTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/EditMenuBuilderTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/InsertMenuBuilderTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/RowContextMenuTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/ViewMenuBuilderTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/BaseGuidedDecisionTablePresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenter_AuditLogTest.java
See https://issues.jboss.org/browse/DROOLS-2149
The problem was that when the editor was opened the menus' state is set based on the "selected decision table". At the point of opening there has been no request for the "lock state" and hence the file appears unlocked and the menus enabled. However when the async call to retrieve the "lock state" completes the file becomes locked and the menus should be disabled.
This PR introduces a new ```RefreshMenusEvent``` that is fired when the "lock state" has been retrieved causing the menus to refresh themselves. Tried and tested locally (what is nice is that when a file is locked, as per the JIRA, and then becomes unlocked the menus in the other users browser update to become enabled).
=> DROOLS-2149: Row and column can be added to read only table

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/wizard/table/pages/ActionSetFieldsPageViewImpl.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/wizard/table/pages/ActionSetFieldsPageTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/wizard/table/pages/ActionSetFieldsPageViewImplTest.java
This PR focus on a case when the TableWizard informs the user about no available pattenrs which could be used in the table actions. In other words, user can not change a field of a pattern because there is no pattern defined yet.
This PR is part of migration form internal selenium test suite into community. See BAQE-314.
@manstis please have a look. This is corollary of #738 .
=> [7.5.x] Increase the TableWizard coverage

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/wizard/table/pages/ActionSetFieldsPageViewImpl.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/wizard/table/pages/ActionSetFieldsPageTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/wizard/table/pages/ActionSetFieldsPageViewImplTest.java
This PR focus on a case when the TableWizard informs the user about no available pattenrs which could be used in the table actions. In other words, user can not change a field of a pattern because there is no pattern defined yet.
This PR is part of migration form internal selenium test suite into community. See BAQE-314.
@manstis please have a look.
=> Increase the TableWizard coverage

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/BaseGuidedDecisionTableEditorPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/BaseGuidedDecisionTableEditorPresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableGraphEditorPresenterTest.java
See https://issues.jboss.org/browse/GUVNOR-3486
This is the corollary of https://github.com/kiegroup/drools-wb/pull/726 for 7.5.x
(cherry picked from commit dc4f41d1217b48ad0da971517d0b9e0f0f98557a)
=> [7.5.x] GUVNOR-3486: [Guided Decision Table Graph] Refresh after removal of table

drools-wb-screens/drools-wb-guided-dtree-editor/drools-wb-guided-dtree-editor-client/src/main/java/org/drools/workbench/screens/guided/dtree/client/widget/shapes/BaseGuidedDecisionTreeShape.java, drools-wb-screens/drools-wb-guided-dtree-editor/drools-wb-guided-dtree-editor-client/src/main/java/org/drools/workbench/screens/guided/dtree/client/widget/shapes/NodeLabel.java
See https://issues.jboss.org/browse/DROOLS-2181
This is the corollary of https://github.com/kiegroup/drools-wb/pull/740 for 7.5.x
(cherry picked from commit b6b2bc812106b1d35ba83e38c93f65af4bc1e135)
=> [7.5.x] DROOLS-2181: Icons (Edit, Collapse, Delete etc) do not respond to mouse clicks

drools-wb-services/drools-wb-verifier/drools-wb-verifier-backend/src/main/resources/org/drools/workbench/services/verifier/webworker/linker/ScriptTemplate.js
https://issues.jboss.org/browse/DROOLS-2229
So the window is actually never used for anything useful, since the web worker can not use any UI. Same goes for $wnd and so on. There is no test, only way to test is with Selenium I think.
=> DROOLS-2229 : Error shown every time GDT editor opened in Firefox and IE11

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/resources/org/drools/workbench/screens/guided/dtable/client/resources/i18n/GuidedDecisionTableErraiConstants.properties
See https://issues.jboss.org/browse/DROOLS-2250
This is the corollary of https://github.com/kiegroup/drools-wb/pull/759 for 7.5.x
(cherry picked from commit c87b0971372415102820f6f4493169c3d8b8971b)
=> [7.5.x] DROOLS-2250: Align Engine hints in Decision Table column wizard with BAPL-708

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/analysis/condition/FieldConditionInspectorKey.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/analysis/condition/ConditionInspectorTest.java
See https://issues.jboss.org/browse/RHBPMS-5096
@Rikkola fix and tests.. just want your opinion on whether this is "safe" (as Hash Code is quite important to V&V). All tests in ```drools-wb-guided-dtable-editor-client``` pass. ```master``` branch seems unaffected.
=> [6.5.x] RHBPMS-5096: [GSS](6.4.z) Guided decision table in Business Central failed to load when using functions in BPM Suite 6.4

drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/main/java/org/drools/workbench/screens/testscenario/client/ActivateRuleFlowWidget.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/main/java/org/drools/workbench/screens/testscenario/client/CallMethodWidget.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/main/java/org/drools/workbench/screens/testscenario/client/ExpectPanel.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/main/java/org/drools/workbench/screens/testscenario/client/FactDataWidgetFactory.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/main/java/org/drools/workbench/screens/testscenario/client/FactWidget.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/main/java/org/drools/workbench/screens/testscenario/client/ListEditorRow.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/main/java/org/drools/workbench/screens/testscenario/client/ListEditorRow.ui.xml, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/main/java/org/drools/workbench/screens/testscenario/client/RetractWidget.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/main/java/org/drools/workbench/screens/testscenario/client/VerifyFactWidget.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/main/java/org/drools/workbench/screens/testscenario/client/VerifyFactsPanel.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/main/java/org/drools/workbench/screens/testscenario/client/VerifyRulesFiredWidget.java
This is corollary of #723,
@ibek asked me to cherry-pick as this is part of Getting Started Experience requirement targeted for RHDM-7.0.GA.
=> [7.5.x] DROOLS-2160: Convert delete buttons to gwt-bootstrap3 (#723)

drools-wb-screens/drools-wb-drl-text-editor/drools-wb-drl-text-editor-backend/src/test/java/org/drools/workbench/screens/drltext/backend/server/DRLTextEditorServiceImplCDITest.java, drools-wb-screens/drools-wb-drl-text-editor/drools-wb-drl-text-editor-backend/src/test/resources/org/drools/workbench/screens/drltext/backend/server/drl/src/main/java/org/kiegroup/storage/Storage.java, drools-wb-screens/drools-wb-drl-text-editor/drools-wb-drl-text-editor-backend/src/test/resources/org/drools/workbench/screens/drltext/backend/server/drl/src/main/resources/org/kiegroup/addAdditionalStorage.drl, drools-wb-screens/drools-wb-drl-text-editor/drools-wb-drl-text-editor-backend/src/test/resources/org/drools/workbench/screens/drltext/backend/server/drl/src/main/resources/org/kiegroup/addAdditionalStorageBroken.drl, drools-wb-screens/drools-wb-drl-text-editor/drools-wb-drl-text-editor-backend/src/test/resources/org/drools/workbench/screens/drltext/backend/server/drl/src/main/resources/org/kiegroup/applyForCarDrivingLicenseAndStore.drl, drools-wb-screens/drools-wb-drl-text-editor/drools-wb-drl-text-editor-backend/src/test/resources/org/drools/workbench/screens/drltext/backend/server/drl/src/main/resources/org/kiegroup/applyForCarDrivingLicenseAndStoreBroken.drl, drools-wb-screens/drools-wb-drl-text-editor/drools-wb-drl-text-editor-backend/src/test/resources/org/drools/workbench/screens/drltext/backend/server/drl/src/main/resources/org/kiegroup/globalStorage.gdrl
This PR increases validation coverage of:
- DRL file with global varaible
- DRL file with explicit import
This is **cherry-pick** of #779
=> [7.5.x] BAQE-336: Increase coverage of drl file validation

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/resources/org/drools/workbench/screens/guided/dtable/client/resources/i18n/GuidedDecisionTableErraiConstants.properties
(cherry picked from commit f68c96ca7432a3787f9dadb9387f109bdc8227ea)
And the same for 7.5.x
=> [7.5.x] DROOLS-2263: Unexpected results in GDST when using enumerations with commas - info

drools-wb-screens/drools-wb-drl-text-editor/drools-wb-drl-text-editor-backend/src/test/java/org/drools/workbench/screens/drltext/backend/server/DRLTextEditorServiceImplCDITest.java, drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-backend/src/test/java/org/drools/workbench/screens/dtablexls/backend/server/DecisionTableXLSServiceImplCDITest.java, drools-wb-screens/drools-wb-enum-editor/drools-wb-enum-editor-backend/src/test/java/org/drools/workbench/screens/enums/backend/server/EnumServiceImplCDITest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/src/test/java/org/drools/workbench/screens/guided/dtable/backend/server/GuidedDecisionTableEditorServiceImplCDITest.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-backend/src/test/java/org/drools/workbench/screens/guided/rule/backend/server/GuidedRuleEditorServiceImplCDITest.java
@manstis please could you have a look?
This could "fix" [the problem](https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/drools-wb-pullrequests-7.5.x/46/testReport/org.drools.workbench.screens.dtablexls.backend.server/DecisionTableXLSServiceImplCDITest/testValidateColumnsNotInStandardOrder/), however I admit "fix" is not the right word. It is like hiding symptoms. I am sorry but I am not able to reproduce locally so this is the most I was able to do. Any hints?
=> DROOLS-2218: Catch NPE in CDI tests cleanup

drools-wb-webapp/pom.xml
@porcelli could you review?
https://issues.jboss.org/browse/RHDM-349
Related to:
https://github.com/kiegroup/optaplanner-wb/pull/250
https://github.com/kiegroup/drools-wb/pull/799
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/692
https://github.com/kiegroup/kie-wb-distributions/pull/685
https://github.com/kiegroup/kie-wb-playground/pull/46
https://github.com/kiegroup/jbpm-wb/pull/980
https://github.com/kiegroup/kie-wb-common/pull/1411
=> [RHDM-349]: Added drools playground dependency

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/BaseGuidedDecisionTableEditorPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/InsertMenuBuilder.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/page/ColumnsPagePresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerView.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/columns/control/AttributeColumnConfigRow.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/columns/control/ColumnManagementView.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/lockmanager/GuidedDecisionTableLockManagerImpl.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/BaseGuidedDecisionTableEditorPresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableGraphEditorPresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/menu/InsertMenuBuilderTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/page/ColumnsPagePresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTableModellerPresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/columns/control/AttributeColumnConfigRowTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/columns/control/ColumnManagementViewTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/lockmanager/GuidedDecisionTableLockManagerImplTest.java
See https://issues.jboss.org/browse/DROOLS-2371
The problem I found was that with a GDT open and then opening a GDTG(raph) and adding the same GDT a ```DecisionTableSelectedEvent``` was raised. The event held a different instance of the first GDT and hence the singular GDT editor set its "active decision table" to ```null```. However the same event also causes the "Columns" tab to refresh itself assuming the "active decision table" is not null... <bang!>
This PR fixes that and also safe guards against similar (undetected) issues by making "active decision table" a ```java.util.Optional``` and refactoring the old use of it accordingly. There will no doubt need to be some tests written (there are no new ones in this PR at the moment) but I thought it worth checking with you both that this …
=> DROOLS-2371: Unable to complete your request. The following exception occurred: (TypeError) in Guided Decision Table Graph

drools-wb-webapp/pom.xml, drools-wb-webapp/src/main/resources/org/drools/workbench/DroolsWorkbench.gwt.xml
https://github.com/kiegroup/appformer/pull/247
https://github.com/kiegroup/kie-wb-common/pull/1511
https://github.com/kiegroup/kie-wb-distributions/pull/709
https://github.com/kiegroup/drools-wb/pull/832
=> [AF-1074]: Removed unused OrganizationalUnitManager View that made connected clients crash.

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/lockmanager/GuidedDecisionTableLockManagerImpl.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/lockmanager/GuidedDecisionTableLockManagerImplTest.java
See https://issues.jboss.org/browse/RHBA-415
Before:
After:
---
- https://github.com/kiegroup/appformer/pull/275
- https://github.com/kiegroup/drools-wb/pull/842
=> RHBA-415: After rename, designer is not marked as dirty more

drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-client/src/main/java/org/drools/workbench/screens/guided/rule/client/widget/attribute/EditAttributeWidgetFactory.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-client/src/main/java/org/drools/workbench/screens/guided/rule/client/widget/attribute/RuleAttributeWidget.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-client/src/test/java/org/drools/workbench/screens/guided/rule/client/widget/attribute/EditAttributeWidgetFactoryTest.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-client/src/test/java/org/drools/workbench/screens/guided/rule/client/widget/attribute/RuleAttributeWidgetTest.java
This PR is corollary of the selenium tests migration effort. This particular PR focus on tests for date attributes widgets. For more detauls see:
https://issues.jboss.org/browse/BAQE-381
@manstis this PR is dependent on #863 . I will mark this as ready for review & merge once we get those in.
=> BAQE-381: Increase coverage of guided rule date attributes

drools-wb-webapp/pom.xml
Hello @manstis,
I'm introducing a new profile that will enable to skip gwt compilation of showcases in `downstream-pullrequests` jobs. In normal build, nothing is skipped. Only when you add `-Pno-showcase` to mvn command line, the showcases won't be gwt-compiled.
https://github.com/kiegroup/jbpm-wb/pull/1160
https://github.com/kiegroup/kie-wb-common/pull/1917
https://github.com/kiegroup/drools-wb/pull/877
https://github.com/kiegroup/appformer/pull/401
=> AF-1248: Add profile to enable skipping of gwt compilation of showcases

drools-wb-webapp/src/main/java/org/drools/workbench/client/DroolsWorkbenchEntryPoint.java, drools-wb-webapp/src/test/java/org/drools/workbench/client/DroolsWorkbenchEntryPointTest.java
Related:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/770
https://github.com/errai/errai/pull/350
https://github.com/kiegroup/appformer/pull/404
https://github.com/kiegroup/kie-wb-common/pull/1925
https://github.com/kiegroup/drools-wb/pull/878
https://github.com/kiegroup/jbpm-wb/pull/1162
https://github.com/kiegroup/optaplanner-wb/pull/288
https://github.com/kiegroup/kie-wb-distributions/pull/773
=> AF-1226: Improve error handling displaying additional info to the GenericErrorPopup

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/src/main/java/org/drools/workbench/screens/guided/dtable/backend/server/indexing/GuidedRuleModelIndexVisitor.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/src/test/java/org/drools/workbench/screens/guided/dtable/backend/server/indexing/GuidedDecisionTableFactory.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/src/test/java/org/drools/workbench/screens/guided/dtable/backend/server/indexing/IndexGuidedDecisionTableBRLFragmentConditionsPredicateTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/src/test/java/org/drools/workbench/screens/guided/dtable/backend/server/indexing/classes/Applicant.java
See https://issues.jboss.org/browse/RHBRMS-3103
The fix for ```6.5.x``` is to skip constraints that cannot be indexed (vs throwing the NPE).
This is different to ```master``` as the codebases have diverged and ```master``` does not _visit_ the model.
=> [6.5.x] GUVNOR-3244 (RHBRMS-3103): [GSS] (6.4.z) "Parameter named 'fieldName' should be not null" when indexing a GDST with BRL fragment eval

drools-wb-webapp/src/main/java/org/drools/workbench/client/DroolsWorkbenchEntryPoint.java, drools-wb-webapp/src/test/java/org/drools/workbench/client/DroolsWorkbenchEntryPointTest.java
This is already merged in 7.7.x. Cherry-picking to master.
Related:
https://github.com/errai/errai/pull/352
https://github.com/kiegroup/appformer/pull/412
https://github.com/kiegroup/kie-wb-common/pull/1951
https://github.com/kiegroup/drools-wb/pull/883
https://github.com/kiegroup/jbpm-wb/pull/1169
https://github.com/kiegroup/optaplanner-wb/pull/290
https://github.com/kiegroup/kie-wb-distributions/pull/776
=> [master] AF-1226: Improve error handling displaying additional info to the GenericErrorPopup

drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-api/pom.xml, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-api/src/main/java/org/drools/workbench/screens/testscenario/type/TestScenarioResourceTypeDefinition.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-backend/src/test/java/org/drools/workbench/screens/testscenario/backend/server/indexing/IndexTestScenarioTest.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/main/java/org/drools/workbench/screens/testscenario/client/type/TestScenarioResourceType.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/test/java/org/drools/workbench/screens/testscenario/client/ScenarioEditorPresenterTest.java
- Move Test Scenario resource type to Decision category.
- ~Move WorkItem resource type to Process category.~
Related PRs:
kiegroup/appformer/pull/438
kiegroup/kie-wb-common/pull/2048
kiegroup/drools-wb/pull/914
kiegroup/optaplanner-wb/pull/296
=> PLANNER-1159: Improve categories

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/pom.xml, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/columns/ConsumerFactory.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/columns/DateUiColumn.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/columns/dom/datepicker/DatePickerSingletonDOMElementFactory.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/columns/ConsumerFactoryTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/columns/DateUiColumnTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/columns/dom/datepicker/DatePickerSingletonDOMElementFactoryTest.java
See:
https://issues.jboss.org/browse/DROOLS-2777
---
Demo:
- First, we need to set the `user.timezone` property:
- ..and then, we can change the timezone to **"Europe/Vilnius"** in the server (`systemsetup -settimezone Europe/Vilnius`):
- ..or even change to **"Europe/Prague"** (`systemsetup -settimezone Europe/Prague`):
..the client side is always using the timezone from the server (from `user.timezone`), so the displayed value will always be consistent.
cc @etirelli 
---
- https://github.com/kiegroup/kie-wb-common/pull/2038
- https://github.com/kiegroup/drools-wb/pull/911
=> DROOLS-2777: Guided Decision Table is changing date field value based on the timezone

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/AppendColumnCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/InsertColumnCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/PrependColumnCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/models/ScenarioGridModel.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/renderers/ScenarioGridColumnRenderer.java
@kkufova @danielezonca 
Scope of this PR is to remove the "collapsing cell" behaviour.
Beside that, the second header level label generation has been modified, so that the number appearing to the right is always incremented, regardless of where the column is actually put.
This PR should be quick to check and has a minimal impact, so if everything is ok it could be merged before 2902
=> [DROOLS-2981] Fix collapsing cell/label default naming

drools-wb-webapp/pom.xml
@Rikkola @manstis @porcelli @danielezonca 
Scope of this PR is to fix the dependency declaration of drool verifier api inside drools-wb-webapp
drools-wb-verifier-api -> drools-verifier-api
Currently, enforcer find "drools-verifier-api" as transitive dependency, while in the pom the drools-wb-verifier-api one is declared.
=> [DROOLS-3033] Fixing dependency declaration of drools-verifier-api

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/InsertColumnCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/SetColumnValueCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/handlers/ScenarioSimulationGridPanelClickHandler.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/metadata/ScenarioHeaderMetaData.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/models/ScenarioGridModel.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/utils/ScenarioSimulationUtils.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/widgets/ScenarioGridColumn.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/AbstractCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/SetColumnValueCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/AbstractScenarioSimulationEditorTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorPresenterTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/metadata/ScenarioHeaderMetaDataTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/models/ScenarioGridModelTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/utils/ScenarioSimulationUtilsTest.java
@jomarko @Rikkola @danielezonca 
Scope of this PR is to avoid calling "getHeaderMetadata().get(1) to retrieve the column information shown on grid. To realize that, the "InformationHeaderMetaData"  has been introduced inside ScenarioGridColumn.
This modification has impact on all the grid rendering, but it should be absolutely transparent for the final user.
=> Drools 3035 - Implement meaningful access to "significant" header metadata

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/AppendColumnCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/AppendRowCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/DeleteColumnCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/DeleteRowCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/DuplicateRowCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/InsertColumnCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/InsertRowCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/PrependColumnCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/PrependRowCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/factories/ScenarioCellTextBoxDOMElement.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/models/ScenarioGridModel.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/widgets/ScenarioGrid.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/AppendColumnCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/AppendRowCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/DeleteColumnCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/DeleteRowCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/DuplicateRowCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/InsertColumnCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/InsertRowCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/PrependColumnCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/PrependRowCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/models/ScenarioGridModelTest.java
@jomarko @Rikkola @danielezonca 
Scope of this pr is to refactor ScenarioGridModel methods names to reflect following contract: "overrided" methods works on both basegrid and scenariosimulation models, "GridOnly" ones works only on basegrid model.
This modification has impact on all the grid rendering, but it should be absolutely transparent for the final user.
=> [DROOLS-3044] Update ScenarioGridModel inherited methods to align Simulation model

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-api/pom.xml, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-api/src/main/java/org/drools/workbench/screens/scenariosimulation/model/FactMappingValue.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-api/src/test/java/org/drools/workbench/screens/scenariosimulation/model/FactMappingValueTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-api/src/test/java/org/drools/workbench/screens/scenariosimulation/model/SimulationTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/pom.xml, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/ScenarioRunnerServiceImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/runner/ScenarioRunnerHelper.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/runner/ScenarioRunnerImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/util/ScenarioBeanUtil.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/ScenarioRunnerImplServiceImplTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/runner/ScenarioRunnerHelperTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/runner/ScenarioRunnerImplHelperTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/util/ScenarioBeanUtilTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/models/ScenarioGridModel.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/RightPanelViewImpl.html, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/utils/ScenarioSimulationUtils.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/utils/ScenarioSimulationUtilsTest.java
Set of minor changes and fixes discovered during a real end to end test of Scenario Simulation
@Rikkola @jomarko @gitgabrio 
Client changes:
- Updated factIdentifier generation for column type binding (no more random columnId generator)
- Hidden "Other" header in the grid
- Hidden right panel mocked component
Backend changes:
- Added support to boolean values into scenario runner
- Better `null` handling in grid values parsing
- Added check on not verifiable "expected" conditions
- Updated runner to use KieContainer classLoader to insert test facts
- Minor improvement in `navigateToBean` method
=> [DROOLS-3060] Perform an end to end test for Scenario asset

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-api/src/main/java/org/drools/workbench/screens/scenariosimulation/model/Scenario.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorPresenterTest.java
@jomarko @Rikkola @danielezonca 
Scope of this PR is to retrieve and store actual package for data objects.
To check:
when using imported Data Objects, running test should not fail with the message " Impossible to load class " followed by a DO with the wrong package name.
=> [DROOLS-3073] Retrieving and using actual package name for Data Objects.

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-api/src/main/java/org/drools/workbench/screens/scenariosimulation/model/FactIdentifier.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-api/src/main/java/org/drools/workbench/screens/scenariosimulation/model/ScenarioSimulationModel.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/AbstractCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/AppendColumnCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/DeleteColumnCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/InsertColumnCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/PrependColumnCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/SetColumnValueCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/handlers/ScenarioSimulationGridPanelClickHandler.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/handlers/ScenarioSimulationGridPanelDoubleClickHandler.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/models/ScenarioGridModel.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/resources/i18n/ScenarioSimulationEditorConstants.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/utils/ScenarioSimulationBuilders.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/utils/ScenarioSimulationUtils.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/widgets/ScenarioGrid.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/widgets/ScenarioGridColumn.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/resources/org/drools/workbench/screens/scenariosimulation/client/resources/i18n/ScenarioSimulationEditorConstants.properties, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/AbstractCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/AppendColumnCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/CommandExecutorTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/DeleteColumnCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/InsertColumnCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/PrependColumnCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/SetColumnValueCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/utils/AbstractUtilsTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/utils/ScenarioSimulationBuildersTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/utils/ScenarioSimulationUtilsTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/widgets/ScenarioGridTest.java
Scope of this PR is to implement read only mechanism for the cells in Scenario grid.
More specifically:
1) Index column should never be editable
2) description column should always be editable
3) GIVEN/EXPECTED columns should not be editable if not mapped to a real property
Different placeholder messages should appear in the different condition (empty editable cell vs not editable one)
Cell editing should start with single click
=> Drools 3052 Implement read only mechanism for the cells in Scenario grid

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/handlers/ScenarioSimulationGridPanelClickHandler.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/widgets/ScenarioGridCell.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/handlers/AbstractScenarioSimulationGridPanelClickHandlerTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/handlers/ScenarioSimulationGridPanelClickHandlerTest.java
Clicking on a Grid cell toggle it to editing mode (insert a ScenarioGrdiCell); but clicking again on the same cell while editing will insert a new ScenarioGridCell inside the previous one.
Scope of this PR is to fix these mis-behavior.
To verify: repeatedly click on same cell should start its editing but no "nested" cell should be created (look at attachment here https://issues.jboss.org/browse/DROOLS-3124 to see how a "nested" cell appear)
=> [DROOLS-3124] Nested GridCell/GridCellValue

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/RightPanelViewImpl.html
Scope of this PR is to remove the vertical scroll bar from RightPanel.
Both scrollbars (horizontal and vertical) should appear only when needed (i.e the content is extending the visible margins) and automatically disappear when not needed.
=> [DROOLS-3170] Removing vertical scroll bar from RightPanel

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-api/src/main/java/org/drools/workbench/screens/scenariosimulation/model/ScenarioSimulationModel.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/ScenarioSimulationXMLPersistence.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/util/InMemoryMigrationStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/util/MigrationStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/ScenarioSimulationXMLPersistenceTest.java
Define automatic migration mechanism. It is in memory for now to be compatible with both internal WB and external maven runner.
@kkufova @Rikkola @gitgabrio
=> [DROOLS-3290] Bump scesim file version to 1.1, added automatic migration support (in memory for now)

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/pom.xml, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/fluent/ValidateFactCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/fluent/ValidateFactCommandTest.java
As discussed I moved RegistryContext to kie-internal end updated usages.
@mariofusco @kkufova
PR list:
https://github.com/kiegroup/droolsjbpm-knowledge/pull/348
https://github.com/kiegroup/drools/pull/2174
https://github.com/kiegroup/drools-wb/pull/1012
https://github.com/kiegroup/jbpm/pull/1387
https://github.com/kiegroup/droolsjbpm-integration/pull/1657
=> [DROOLS-3177] Move RegistryContext to kie-internal

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/fluent/ScenarioExecutableBuilder.java
As discussed, this PR move to kie-internal the fluent API because it is still experimental
@mariofusco @mdproctor @kkufova 
PRs list:
https://github.com/kiegroup/droolsjbpm-knowledge/pull/349
https://github.com/kiegroup/drools/pull/2177
https://github.com/kiegroup/drools-wb/pull/1016
https://github.com/kiegroup/droolsjbpm-integration/pull/1661
=> [DROOLS-3401] Moved Fluent API to kie-internal

drools-wb-webapp/pom.xml
Hey @ederign @hasys @manstis 
See https://issues.jboss.org/browse/JBPM-8026
The `kie-wb-common-stunner-backend` is only necessary when the backend does not support guvnor and some other kie modules, which is not the case of this webapp. So this dependency can be removed. Also by removing it, the `stunner.git` repository will be never created. I've tested the webapp and it works.
Thanks!
=> JBPM-8026: Remove unnecessary dependency to stunner standalone backend module

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/utils/ScenarioSimulationGridHeaderUtilities.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/utils/ScenarioSimulationGridHeaderUtilitiesTest.java
@kkufova @jomarko @Rikkola 
That loop was caused by a change inside upper layer.
Before this change, by default ScenariogridModel had 1 header row, even when called by the default constructor. After the change, the default header row number is 0.
Inside ScenarioSimulationGridHeaderUtilities there is a method that uses that row number in a "while" loop for a subtraction, but since now that number is 0, that loop will never end.
The fix has been to check for "0" rows before that loop, eventually returning null.
Tests have been modified as per @jomarko suggestion. A new one has been added.
Please check ASAP to merge it.
=> [DROOLS-3417] Avoiding endless loop on ScenarioSimulationGridHeaderUtilitiesTest

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/actualcommands/SetInstanceHeaderCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/actualcommands/SetPropertyHeaderCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/actualcommands/SetInstanceHeaderCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/actualcommands/SetPropertyHeaderCommandTest.java
@kkufova @danielezonca @Rikkola 
Scope of this PR is to prevent header editing when adding column inside a DMN scenario simulation
=> [DROOLS-3471] Prevent header editing when adding column in DMN scenario

drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-backend/src/test/java/org/drools/workbench/screens/dtablexls/backend/server/DecisionTableXLSServiceImplCDITest.java, drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-backend/src/test/java/org/drools/workbench/screens/dtablexls/backend/server/conversion/DTCellValueUtilitiesStripQuotesTest.java, drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-backend/src/test/java/org/drools/workbench/screens/dtablexls/backend/server/conversion/DTCellValueUtilitiesTest.java, drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-backend/src/test/java/org/drools/workbench/screens/dtablexls/backend/server/conversion/DecisionTableXLSToDecisionTableGuidedConverterTest.java, drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-backend/src/test/java/org/drools/workbench/screens/dtablexls/backend/server/conversion/GuidedDecisionTableGeneratorListenerTest.java
Replacement of #870 
@manstis would you mind to have a look?
I find out the problem is caused by `DecisionTableXLSServiceImplCDITest`. There I set the system property `drools.dateformat`. I debugged hours today, but didn't find out, why the system property from that test is propagated also to other tests, even when I do clean up in `@AfterClass` method.
Due to the time I have spent already with the issue I prefer this alternative, much less appropriate, solution.
Please let me know what do you think.
=> DROOLS-2623: Stabilize xls-dtables tests

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/renderers/BaseExpressionGridTheme.java
I made changes to the font of highlighted cells based on [DROOLS-3393](https://issues.jboss.org/browse/DROOLS-3393).
**This should be merged together with: https://github.com/kiegroup/appformer/pull/605.**
The highlighted cells now look as follows:
@danielezonca, @Rikkola, could you please take a look?
=> DROOLS-3435 Change the text color in highlighted cells

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/expression/BaseExpressionOperator.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/runner/AbstractRunnerHelper.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/runner/RuleScenarioRunnerHelper.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/expression/BaseExpressionOperatorTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/runner/RuleScenarioRunnerHelperTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/factories/ScenarioCellTextAreaDOMElement.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/factories/ScenarioCellTextAreaDOMElementTest.java
Now empty cell means to skip it (both for GIVEN/EXPECT).
Rule scesim file you can use `null` as alternative to express a null condition.
DMN scesim now just skip cell if empty or use FEEL unary expression evaluation if not empty
@Rikkola @gitgabrio @kkufova
=> [DROOLS-3472] Change empty cell behavior, from null to skip it

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-api/src/main/java/org/drools/workbench/screens/scenariosimulation/utils/ScenarioSimulationSharedUtils.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/AbstractKieContainerService.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/ScenarioSimulationServiceImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/expression/AbstractExpressionEvaluator.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/expression/BaseExpressionEvaluator.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/expression/BaseExpressionOperator.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/expression/DMNFeelExpressionEvaluator.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/expression/ExpressionEvaluator.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/runner/AbstractRunnerHelper.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/util/DMNSimulationCreationStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/util/DMNSimulationUtils.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/DMNTypeServiceImplTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/ScenarioRunnerServiceImplTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/ScenarioSimulationServiceImplTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/expression/AbstractExpressionEvaluatorTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/expression/BaseExpressionEvaluatorTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/expression/DMNFeelExpressionEvaluatorTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/model/ListMapClass.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/util/DMNSimulationUtilsTest.java
This PR add DMN-related dependencies to user project and improve error message in case of broken KieContainer.
https://issues.jboss.org/browse/DROOLS-3496
https://issues.jboss.org/browse/DROOLS-3473
https://issues.jboss.org/browse/DROOLS-3487
NOTE 1: remove ScenarioJunitActivatorTest in an existing project and create/save a scenario to force pom dependency refresh
NOTE 2: KieContainer is broken if the DMN file has a compilation error or if there are more than a single DMN file with same `namespace` and `name`. Use `Build` button in the asset list page to force KieContainer refresh when the error has been fixed
NOTE 3: to build user project from outside using `mvn package` command, you need first to install locally `drools-wb-scenario-simulation-editor`. If you have a compilation error …
=> [DROOLS-3496][DROOLS-3473][DROOLS-3487] Fix external JUnit runner support for DMN scenarios

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/domelements/CollectionEditorDOMElement.java
@jomarko @danielezonca @Rikkola 
https://issues.jboss.org/browse/DROOLS-3662
=> [DROOLS-3662] Verify Collection editor is always shown on center of the widget

drools-wb-screens/drools-wb-guided-template-editor/drools-wb-guided-template-editor-client/src/main/java/org/drools/workbench/screens/guided/template/client/editor/TemplateDataTableWidget.java
See https://issues.jboss.org/browse/DROOLS-3673
This replaces https://github.com/kiegroup/drools-wb/pull/1072 as a new JIRA was required.
=> DROOLS-3673: Values are getting missed/changed from Guided Rule Template when rows are inserted with + icon

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/ScenarioSimulationServiceImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/ScenarioSimulationServiceImplTest.java
@kkufova @Rikkola @gitgabrio 
How to reproduce:
Import one of the project from https://github.com/kiegroup/kie-wb-playground.git and create a scesim file
Note 1: this PR create a specific package for the ScenarioJunitActivator (`test`) so after the first scesim file, user will have this package in the package list.
Note 2: this PR also remove the ScenarioJunitActivator file from the old position if exists. The old position is the package equivalent to the groupId so usually `com.myspace`
=> [RHPAM-1923] Fix ScenarioJunitActivator creation

drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/main/java/org/drools/workbench/screens/testscenario/client/page/audit/AuditPage.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/main/java/org/drools/workbench/screens/testscenario/client/page/audit/AuditPageViewImpl.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/test/java/org/drools/workbench/screens/testscenario/client/page/audit/AuditPageTest.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/test/java/org/drools/workbench/screens/testscenario/client/page/audit/AuditPageViewImplTest.java
https://issues.jboss.org/browse/DROOLS-3724
@manstis @kkufova  Could you two please take a look.
=> [7.18.x] DROOLS-3724 : Defining non default Kie Base and Kie Session results in a hang in the Test Scenario Runner

drools-wb-screens/drools-wb-guided-template-editor/drools-wb-guided-template-editor-client/src/main/java/org/drools/workbench/screens/guided/template/client/editor/TemplateDataTableWidget.java, drools-wb-screens/drools-wb-guided-template-editor/drools-wb-guided-template-editor-client/src/test/java/org/drools/workbench/screens/guided/template/client/editor/TemplateDataTableWidgetTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/CollectionPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/CollectionView.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/CollectionViewImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/ElementPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/ElementView.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/ItemElementPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/KeyValueElementPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/popup/AbstractScenarioConfirmationPopup.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/popup/AbstractScenarioConfirmationPopupView.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/popup/ConfirmPopupView.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/popup/DeletePopupView.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/popup/PreserveDeletePopupView.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/popup/ScenarioConfirmationPopupPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/popup/ScenarioConfirmationPopupView.html, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/popup/ScenarioConfirmationPopupView.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/popup/YesNoConfirmPopupPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/resources/i18n/ScenarioSimulationEditorConstants.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/resources/org/drools/workbench/screens/scenariosimulation/client/resources/i18n/ScenarioSimulationEditorConstants.properties, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/CollectionPresenterTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/ElementPresenterTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/popup/AbstractDeletePopupViewTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/popup/AbstractScenarioConfirmationPopupViewTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/popup/ConfirmPopupViewTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/popup/DeletePopupViewTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/popup/PreserveDeletePopupViewTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/popup/ScenarioConfirmationPopupViewPresenterTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/popup/ScenarioConfirmationPopupViewTest.java, drools-wb-webapp/pom.xml
@ederign @porcelli @manstis @Rikkola @danielezonca @etirelli 
The main scope of this PR is to allow editing/debugging/hot-reload client-code (GWT) of modules external of drools-wb while working with drools-webapp. This should be configurable on a per-developer basis, modifying personal .m2/settings.xml, without touching the versioned pom.xml
The current solution is based on the build-helper-maven-plugin, but it has two limitations
1) it is needed to statically define every external source inside the plugin configuration
2) it is not possible to override such configuration with the user' .m2/settings.xml.
The gwt-help-maven-plugin (https://github.com/gitgabrio/gwt-helper-maven-plugin) has been designed to overcome this limitations, following suggestions from @ederign:
1) it uses a pattern …
=> [DROOLS-3654] Replacing build-helper-maven-plugin with gwt-helper-maven plugin

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/handlers/CommonEditHandler.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/widgets/ScenarioGridColumn.java
https://issues.jboss.org/browse/DROOLS-3767
To avoid the described (and wrong) behaviour, a try - catch block was added in `ScenarioGridModel.edit()` method. Then, is ANY execption is catched, the "isEditing" status is reset as required.
About tests: in my opinion the current tests are enough: I don't know how to test the case where an exception is thrown during the process, feel free to give me some advice.
@danielezonca @gitgabrio  @kkufova please review.
=> [DROOLS-3767] Reset "isEditing" status flag inside gridcell

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/actualcommands/AbstractScenarioSimulationCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/handlers/CommonEditHandler.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/utils/ScenarioSimulationGridHeaderUtilities.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/actualcommands/AbstractScenarioSimulationCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/utils/ScenarioSimulationGridHeaderUtilitiesTest.java
There were two issues:
- `AbstractScenarioSimulationCommand.commonExecution` previously re-enforced grid panel focusing for all commands. This focus was causing flushing `ScenarioHeaderTextAreaDOMElement` and this edit box was immediatelly discarded. Now `AbstractScenarioSimulationCommand.commonExecution` re-enforces grid panel focus, just for commands that change grid structure, for example append row, column, etc.
- `ScenarioSimulationGridHeaderUtilities` contained two methods for edit header precondition (`isEditableHeader` and `isHeaderEditable`) while the second one wasn't used at all but still contained valid logic. Now both are merged and used in `CommonEditHandler.manageHeaderLeftClick`
@kkufova @gitgabrio could you please take a look when you have a moment. Thank you in advance.
=> DROOLS-3752: Update header cells edit mode invocation

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/pom.xml, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/DMNTypeServiceImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/ScenarioSimulationServiceImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/fluent/DMNScenarioExecutableBuilder.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/runner/AbstractRunnerHelper.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/runner/DMNScenarioRunnerHelper.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/runner/model/ScenarioGiven.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/runner/DMNScenarioRunnerHelperTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/runner/RuleScenarioRunnerHelperTest.java
@kkufova @gitgabrio @Rikkola 
How to test:
- Import a dmn file with an input constraint like [DMNString.dmn.txt](https://github.com/kiegroup/drools-wb/files/3005478/DMNString.dmn.txt) (remove `.txt`)
- Create a scesim file on it
- Put an invalid input (accepted values are only `"Example1"`, `"Example2"` and `"Example3"`)
- Run
https://issues.jboss.org/browse/DROOLS-3730
=> [DROOLS-3730] Add support to DMN constraints on inputs (report input validation errors)

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/analysis/AnalyzerConfigurationMock.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-guided-decision-table-adapter/src/main/java/org/drools/workbench/services/verifier/plugin/client/AnalyzerBuilder.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-guided-decision-table-adapter/src/main/java/org/drools/workbench/services/verifier/plugin/client/DTableUpdateManager.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-guided-decision-table-adapter/src/main/java/org/drools/workbench/services/verifier/plugin/client/RegularCellUpdateManager.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-guided-decision-table-adapter/src/main/java/org/drools/workbench/services/verifier/plugin/client/builders/BRLConditionBuilder.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-guided-decision-table-adapter/src/main/java/org/drools/workbench/services/verifier/plugin/client/builders/FieldConditionBuilder.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-guided-decision-table-adapter/src/main/java/org/drools/workbench/services/verifier/plugin/client/builders/TypeResolver.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-guided-decision-table-adapter/src/main/java/org/drools/workbench/services/verifier/plugin/client/builders/Utils.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-guided-decision-table-adapter/src/main/java/org/drools/workbench/services/verifier/plugin/client/builders/UtilsTypeResolver.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-guided-decision-table-adapter/src/main/java/org/drools/workbench/services/verifier/plugin/client/builders/ValuesResolver.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-guided-decision-table-adapter/src/test/java/org/drools/workbench/services/verifier/plugin/client/AnalyzerUpdateTestBase.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-guided-decision-table-adapter/src/test/java/org/drools/workbench/services/verifier/plugin/client/NoOperatorTest.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-guided-decision-table-adapter/src/test/java/org/drools/workbench/services/verifier/plugin/client/testutil/AnalyzerBuilder.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-guided-decision-table-adapter/src/test/java/org/drools/workbench/services/verifier/plugin/client/testutil/DateTimeFormatProviderMock.java, drools-wb-services/drools-wb-verifier/drools-wb-verifier-guided-decision-table-adapter/src/test/java/org/drools/workbench/services/verifier/plugin/client/testutil/ExtendedGuidedDecisionTableBuilder.java
https://issues.jboss.org/browse/DROOLS-1797
@jomarko @manstis I would appreciate reviews on these two PRs.
I touched several locations just to get the info about field type. 
Main change is that it is possible to detect the value and operator from the cell.
Another change is that updates should now go more smoothly for existing edits since update manager now uses ValuesResolver. The updates also support changing the condition operator.
Part of a bundle:
https://github.com/kiegroup/drools/pull/2289
https://github.com/kiegroup/drools-wb/pull/1104
=> DROOLS-1797 : Incorrect V&V results when operator is filled in the row

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/actualcommands/AbstractSetHeaderCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/actualcommands/SetPropertyHeaderCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/AbstractScenarioSimulationTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/actualcommands/SetPropertyHeaderCommandTest.java
https://issues.jboss.org/browse/DROOLS-3818
Steps to reproduce it:
- Open a new scenario asset
- Assign a instance (eg . Author)
- Rename it (eg. Author_test)
- Try to assign a Complex type as a property (eg. a Collection)
- A NPE is thown.
Basically, the issue was in SetPropertyHeaderCommand.java lines 71/72, where it tried to FactModelTree using the aliasName (column title) instead of the fact classname.
Some variable has been renamed to avoid confusion beetween aliasName and className.
@kkufova @gitgabrio @danielezonca please test it and review.
=> [DROOLS-3818] Assign a complex type object to a property with modified label leads to NPE

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/resources/i18n/ScenarioSimulationEditorConstants.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/resources/org/drools/workbench/screens/scenariosimulation/client/resources/i18n/ScenarioSimulationEditorConstants.properties, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorPresenterTest.java
https://issues.jboss.org/browse/DROOLS-3883
NOTE: the indicator was already removed in case of exception by `HasBusyIndicatorDefaultErrorCallback` 
@kkufova @Rikkola @gitgabrio
=> [DROOLS-3883] Add running indicator

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/ScenarioSimulationEventHandler.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/actualcommands/DeleteColumnCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/models/ScenarioGridModel.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/models/ScenarioGridModelTest.java
https://issues.jboss.org/browse/DROOLS-4034
Open a new TestScenario editor.
Try to assign an instance to a column. Instance only, without a property (eg. Author).
An exception is thown.
Issue introduced with fix of ticket DROOLS-3890, please retest this ticket too.
@jomarko  @gitgabrio @danielezonca can you please review it?
Thanks.
=> [DROOLS-4034] Add an Instance to a Scenario Column leads to an exception

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/DMNTypeServiceImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/DMNTypeServiceImplTest.java
@jomarko  @gitgabrio @danielezonca Can you please review it?
The error checking is perfmormed 2 times, so I simply replaced the List with a Set to avoid duplicates.
https://issues.jboss.org/browse/DROOLS-3855
=> [DROOLS-3855] Unsupported DMN asset shows each item two times

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/actualcommands/AbstractScenarioSimulationCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/actualcommands/AbstractSelectedColumnCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/actualcommands/SetGridCellValueCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/AbstractDataManagementStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/DMODataManagementStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/DataManagementStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/SimpleClassEntry.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/models/ScenarioGridModel.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/resources/i18n/ScenarioSimulationEditorConstants.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/CheatSheetViewImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/utils/ConstantHolder.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/utils/ScenarioSimulationUtils.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/widgets/ScenarioGrid.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/resources/org/drools/workbench/screens/scenariosimulation/client/resources/i18n/ScenarioSimulationEditorConstants.properties, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/actualcommands/SetInstanceHeaderCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/AbstractDataManagementStrategyTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/DMODataManagementStrategyTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/utils/ScenarioSimulationUtilsTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/widgets/ScenarioGridTest.java
This PR introduce a basic support for `LocalDate` class to Rule based scenario.
On client side `LocalDate` are managed as simple types so user will need to write the full date in a single cell using the format `yyyy-MM-dd`. A custom placeholder is displayed in `LocalDate`s cells to inform the user about the format.
NOTE: `LocalDate` is not supported by GWT on client side so I had to use hardcoded strings for `simpleName` and `canonicalName` (the only information required on client side)
https://issues.jboss.org/browse/DROOLS-4018
@jomarko @gitgabrio @Rikkola 
PRs list:
- https://github.com/kiegroup/drools-wb/pull/1148
- https://github.com/kiegroup/drools/pull/2359
=> [DROOLS-4018] Add support for LocalDate in Rule based test scenarios

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/importexport/ScenarioCsvImportExport.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/importexport/ScenarioCsvImportExportTest.java
Replace empty string with `null` during import
https://issues.jboss.org/browse/DROOLS-3926
@kkufova @gitgabrio @Rikkola
=> [DROOLS-3926] Passing test scenario with empty cells starts failing after export + import

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/ScenarioSimulationServiceImplTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/handlers/NewScenarioSimulationHandler.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/AbstractScenarioSimulationEditorTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/handlers/NewScenarioSimulationHandlerTest.java
=> [DROOLS-4130] Fix default session name

drools-wb-webapp/pom.xml
See https://issues.jboss.org/browse/DROOLS-4042
Further too https://github.com/kiegroup/kie-wb-common/pull/2683 `drools-wb-webapp` needs a JAXB implementation in order for the PMML integration with DMN to function correctly. `kie-wb-distributions` has a JAXB implementation bundled with it by virtue of depending on `kie-pmml` too.
=> DROOLS-4042: [DMN Designer] Add support for importing and consuming PMML models

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/converters/column/impl/BaseColumnConverterImpl.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/converters/column/impl/GridWidgetColumnFactoryImplTest.java, drools-wb-screens/drools-wb-guided-template-editor/drools-wb-guided-template-editor-client/src/main/java/org/drools/workbench/screens/guided/template/client/editor/TemplateDataCellFactory.java, drools-wb-screens/drools-wb-guided-template-editor/drools-wb-guided-template-editor-client/src/main/java/org/drools/workbench/screens/guided/template/client/editor/TemplateDataCellValueFactory.java, drools-wb-screens/drools-wb-guided-template-editor/drools-wb-guided-template-editor-client/src/test/java/org/drools/workbench/screens/guided/template/client/editor/TemplateDataCellFactoryTest.java
Ensmeble together with:
- https://github.com/kiegroup/drools/pull/2379
This PR fixes the issue in guided rule templates. User was not able to put multiple numeric values separated by comma as the numeric text box was forcing just numbers. This PR change the behavior in the way allowing all characters if the "in" or "not in" operator is selected in the guided rule template.
@Rikkola @Bonuseto may I ask you for a review?
=> DROOLS-4131: Allow any characters for list operators

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/menu/GridContextMenu.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/menu/ScenarioContextMenuRegistry.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/menu/ScenarioContextMenuRegistryTest.java
@kkufova @gitgabrio @danielezonca please review and test it.
To solve the issue, we defined the following updated behaviour:
Columns actions are now present ONLY when you open the menu starting from a HEADER cell.
Therefore, When you right-click from a BODY cell, you will have ONLY items related to row actions.
https://issues.jboss.org/browse/DROOLS-4180
=> [DROOLS-4180] Invoking "duplicate instance" from a row causes unexpected error

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/SettingsPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/SettingsView.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/SettingsViewImpl.html, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/SettingsViewImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/AbstractSettingsTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/SettingsPresenterTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/SettingsViewImplTest.java
This PR enables stateless kieSession testing.
Setting dock now contains a checkbox to specify if the session is stateless or not.
All the existing session settings are supported by stateless kiesession too: it is possible to specify session name and/or ruleFlowGroup/agendaGroup
@kkufova @Rikkola @gitgabrio @yesamer 
https://issues.jboss.org/browse/DROOLS-3775
PR list:
- https://github.com/kiegroup/drools/pull/2405
- https://github.com/kiegroup/drools-wb/pull/1174
=> [DROOLS-3775] Added stateless kiesession support

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/main/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/rightpanel/TestRunnerReportingPanelWrapperImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/TestToolsViewImpl.html
@kkufova @gitgabrio @danielezonca Can you please review it?
Basically, we have 2 changes here:
- Removed a `<BR>` tag on TestTools docks;
- Added a FlowPanel which wraps TestRunnerReportingPanel widget adding the missing padding pixels. Consider that isn't possible to modify the original panel, nor extends it to override its style.
=> [DROOLS-3870] Fix top vertical spaces in test scenario docks

drools-wb-webapp/pom.xml
Adding uberfire-preference-client-backend dependency, which is introduced by: kiegroup/appformer#724
MERGE WITH kiegroup/appformer#724
=> AF-1987: Adding uberfire-preference-client-backend dep

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/BaseGuidedDecisionTableEditorPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableEditorPresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/search/GuidedDecisionTableEditorSearchIndex.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/editor/search/GuidedDecisionTableSearchableElement.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/BaseGuidedDecisionTableEditorPresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/BaseGuidedDecisionTablePresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableEditorMenusTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/GuidedDecisionTableEditorPresenterTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/search/GuidedDecisionTableEditorSearchIndexTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/editor/search/GuidedDecisionTableSearchableElementTest.java
- https://issues.jboss.org/browse/DROOLS-4211
- https://issues.jboss.org/browse/DROOLS-4212
---
- https://github.com/kiegroup/appformer/pull/738
- https://github.com/kiegroup/kie-wb-common/pull/2749
- https://github.com/kiegroup/drools-wb/pull/1191
---
DROOLS-4211 and DROOLS-4212 JIRAs comprehend only the search mechanism. Thus, the PR implements that for Guided Decision Tables, DMN graphs, and DMN boxed expressions, without a rich user experience (which will be implemented on [DROOLS-4306](https://issues.jboss.org/browse/DROOLS-4306)).
To test this PR, just execute the following code into the _browser inspector_:
```javascript
document.querySelector('.kie-search-bar').style.display = ""
```
The search component will be enabled, and now you can type something and press <kbd>Enter</kbd> to …
=> DROOLS-4211 / DROOLS-4212: Search feature - Implement search mechanism PoC on GDT / DMN graph

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/util/DMNSimulationCreationStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/util/RULESimulationCreationStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/util/SimulationCreationStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/util/DMNSimulationCreationStrategyTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/util/SimulationCreationStrategyTest.java
This PR cover these situations:
- DMN model with no elements -> it creates an empty GIVEN column and an empty EXPECT column
- DMN model contains only input nodes -> it adds an empty EXPECT column
- DMN model contains only decision nodes -> it adds an empty GIVEN column
https://issues.jboss.org/browse/DROOLS-4108
@kkufova @yesamer @Rikkola
=>  [DROOLS-4108] Add check to avoid DMN test scenario to be created without any GIVEN or EXPECT column

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/domelements/ScenarioHeaderTextAreaDOMElement.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/models/ScenarioGridModel.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/resources/i18n/ScenarioSimulationEditorConstants.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/widgets/ScenarioGrid.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/resources/org/drools/workbench/screens/scenariosimulation/client/resources/i18n/ScenarioSimulationEditorConstants.properties, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/domelements/ScenarioHeaderTextAreaDOMElementTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/models/ScenarioGridModelTest.java
@dupliaka  @gitgabrio @danielezonca Can you please test it and review?
Currently it is possible to set an empty label in header cell type (instance title or property title). This PR adds a check which prevent it. In that case, an error message is thrown.
https://issues.jboss.org/browse/DROOLS-4571
=> [DROOLS-4571] It's possible to set an empty title header

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/ScenarioSimulationContext.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/handlers/ScenarioInvokeContextMenuForSelectedCell.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/handlers/ScenarioSimulationGridPanelClickHandler.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/handlers/ScenarioSimulationGridWidgetMouseEventHandler.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/handlers/ScenarioSimulationKeyboardEditHandler.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/models/ScenarioGridModel.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/widgets/ScenarioGrid.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/handlers/ScenarioInvokeContextMenuForSelectedCellTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/handlers/ScenarioSimulationGridPanelClickHandlerTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/handlers/ScenarioSimulationGridWidgetMouseEventHandlerTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/handlers/ScenarioSimulationKeyboardEditHandlerTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/models/ScenarioGridModelTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/widgets/ScenarioGridTest.java
@dupliaka @gitgabrio @danielezonca can you please test and review it?
The original GridPanel fully supports cells selection span. I simply restored the native handling removing the wrong overridden logic in ScenarioSimulation code.
Bow works for:
- Left click,
- Right click
- Keyboard navigation
- Double click + editing mode
https://issues.jboss.org/browse/DROOLS-4573
=> [DROOLS-4573] Cell selection doesn't span the entire cell

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/main/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/editor/ScenarioSimulationEditorBusinessCentralWrapper.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/test/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/editor/ScenarioSimulationEditorBusinessCentralWrapperTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/SettingsPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/SettingsView.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/SettingsViewImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/MockProducer.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorPresenterTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/AbstractSettingsTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/SettingsPresenterTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/SettingsViewImplTest.java
@dupliaka  @yesamer @danielezonca
see https://issues.jboss.org/browse/DROOLS-4638
Logic behind the current implementation is:
1) currently, user "credential" as a concept exists only inside BC, not in Kogito
2) as such, I consider the "read/write" permission a BC-specific condition
3) so, main presenter and settings presenter should normally work without such knowledge, and their default editable status is always _true_
4) it is the BC specific component (**ScenarioSimulationEditorBusinessCentralWrapper**) - in case - to "disable" the editable status
5) I had to add the **ScenarioSimulationEditorPresenter.saveEnabled** flag because both the _SettingsPanel_ setup and the retrieval of user "read/write" permissions happen in different - more or less asynchronous - threads, so it is not sure …
=> Drools 4638 - Disable Save button on settings for user without write permission

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorPresenterTest.java
@dupliaka @gitgabrio @danielezonca can you please review / test with high priority? 
https://issues.jboss.org/browse/DROOLS-4676
=> [DROOLS-4676] Scenario run failed when user deletes columns

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/main/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/editor/ScenarioSimulationEditorBusinessCentralWrapper.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorPresenterTest.java
@dupliaka @gitgabrio @danielezonca
Temporary removing  background grid which is still not working, in order to don't include it for 7.29.0 release.
https://issues.jboss.org/browse/DROOLS-4674
=> [DROOLS-4674] Temporary remove background Tab

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/menu/ScenarioContextMenuRegistry.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/widgets/ScenarioGrid.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/AbstractDataManagementStrategyTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/menu/ScenarioContextMenuRegistryTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/widgets/ScenarioGridTest.java
@manstis @Rikkola 
Backporting of https://issues.jboss.org/browse/DROOLS-3969 
https://github.com/kiegroup/drools-wb/pull/1226
(cherry picked from commit 500298a51369c22e130d0c95b8452591e74e8f8b)
=> [DROOLS-3969] Backport to 7.26.x

pom.xml
https://issues.jboss.org/browse/DROOLS-4563
Parent PR:
- kiegroup/droolsjbpm-build-bootstrap#1075
Dependent PRs:
- kiegroup/appformer#814
- kiegroup/kie-wb-common#2934
- kiegroup/drools-wb#1238
- kiegroup/optaplanner-wb/pull/348
=> DROOLS-4563: managing javax.validation-api for GWT code to 1.0.0.GA

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/analysis/DecisionTableAnalyzerTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/model/synchronizers/impl/ConditionColumnSynchronizerTest.java
As part of DROOLS-4650 we implemented equals method of columns. Some tests needed to be updated to differentiate once compared via equals.
Ensemble together with:
https://github.com/kiegroup/drools/pull/2624
=> DROOLS-4650: Fix failing tests

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/TestToolsPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/TestToolsPresenterTest.java
@dupliaka @gitgabrio @danielezonca Can you please test and review it?
Very simple, to solve the reported issues, the tool panel it's now disabled after a grid switching.
We agreed to improve the search functionality in a separate ticket.
https://issues.jboss.org/browse/DROOLS-4804
=> [DROOLS-4804] Disabling TestTools when switching grids

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/main/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/editor/strategies/BusinessCentralDMNDataManagementStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/test/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/editor/strategies/BusinessCentralDMNDataManagementStrategyTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/AbstractDMNDataManagementStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/AbstractDataManagementStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/TestToolsPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/TestToolsPresenterData.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/TestToolsView.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/AbstractDMNDataManagementStrategyTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/AbstractDataManagementStrategyTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/TestToolsPresenterTest.java
@dupliaka @gitgabrio @danielezonca can you please test and review it?
Technical refactoring, no changes on existing functionalities. The aim is to unify the TestTools data population in a single method.
https://issues.jboss.org/browse/DROOLS-4827
=> [DROOLS-4827] Refactoring Test Tool data population

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/pom.xml
During https://github.com/kiegroup/drools-wb/pull/1201 review I found these unused dependencies.
=> DROOLS-3957: Remove unused dependencies

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/resources/css/ScenarioSimulationEditorStylesCss.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/CoverageReportDonutPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/CoverageReportPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/CoverageReportViewImpl.html, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/CoverageScenarioListPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/CoverageScenarioListView.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/CoverageScenarioListViewImpl.html, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/CoverageScenarioListViewImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/resources/org/drools/workbench/screens/scenariosimulation/client/resources/css/ScenarioSimulationEditorStyles.css, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/CoverageReportDonutPresenterTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/CoverageReportPresenterTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/CoverageScenarioListPresenterTest.java
@dupliaka @gitgabrio @danielezonca Can you please test it and review it?
This PR contains some CSS styles change for CoverageScenarioPanel.
The considerable part is the requirement to put the percentage of decision tested INSIDE the hole of the Donut chart.
Related PR: https://github.com/kiegroup/appformer/pull/860
https://issues.jboss.org/browse/DROOLS-4518
=> [DROOLS-4518] Style improvements for CoverageScenario panel

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/utilities/ColumnUtilities.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/utilities/ColumnUtilitiesTest.java
https://issues.redhat.com/browse/DROOLS-4876
The `isValueValidForType `tests with cast if the value is boolean, interger or anything, but String. For String everything goes. This change trims the checked value from the first = character. This means only the actual value is checked and not the alias.
=> DROOLS-4876: GDST: Aliases only work for Strings

drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/main/java/org/drools/workbench/screens/testscenario/client/page/settings/ExecutionWidget.java, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-client/src/test/java/org/drools/workbench/screens/testscenario/client/page/settings/ExecutionWidgetTest.java
See https://issues.redhat.com/browse/RHDM-1198
Before:
After:
=> RHDM-1198: Change use date settings don't be persisted on Test Scenario Legacy

drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-backend/pom.xml
This PR reverts changes of https://github.com/kiegroup/drools-wb/pull/1287
The given dependency is used by DecisionTableXLSServiceImplCDITest
=> Reverting drools-wb-dtable-xls-editor-backend dependency cleanup

pom.xml
@jomarko @rsynek 
There was a configuration in `drools-wb` to skip test execution if test coverage was not enabled for that module
=> Avoid to skip test execution

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/CollectionViewImpl.html, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/CollectionViewImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/factories/CollectionEditorSingletonDOMElementFactory.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/CollectionViewImplTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/factories/CollectionEditorSingletonDOMElementFactoryTest.java
@jomarko @danielezonca 
I simply stopped to propagate the `MouseWheelEvent` on `CollectionEditorSingletonDOMElementFactory`.
I apply the same fix for `ContextMenuEvent` (RightClick), this avoid to select the grid and to open the context menu (current behavior in master) when right-clicking on collection editor popup.
https://issues.redhat.com/browse/DROOLS-4921
=> DROOLS-4921: Scrollbars in collection editor popup do not work

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/DMNScenarioValidation.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/DMNScenarioValidationTest.java
This PR removes a wrong validation check: top level collections were not supported by Test Scenario in the past but after the implementation of the support this check has not been properly updated.
Checking this ticket I have realized that other conditions of validation are not properly covered yet so I have created [this ticket](https://issues.redhat.com/browse/DROOLS-4988). I prefer in this PR to only fix the misleading error message
@yesamer @jomarko 
https://issues.redhat.com/browse/DROOLS-4920
=> [DROOLS-4920] Removed outdated validation check

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/AbstractDMNTest.java
@danielezonca @jomarko @tarilabs 
Considering the changes https://github.com/kiegroup/drools/pull/2741, `isCollection` boolean must be passed to the constructor of `CompositeTypeImpl`, because it's now used to determine the object behavior. Using `setCollection()` method leads to the issue. (It should be handled or, even better, removed)
=> DROOLS-4969: Fixed broken tests after merge of DROOLS-4969

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/FieldItemViewImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/ListGroupItemPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/ListGroupItemViewImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/FieldItemViewTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/ListGroupItemPresenterTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/ListGroupItemViewImplTest.java
For more details see: https://issues.redhat.com/browse/DROOLS-5067
=> DROOLS-5067: Add Bound Fact Property checkmark

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/main/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/editor/ScenarioSimulationEditorBusinessCentralWrapper.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/test/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/editor/ScenarioSimulationEditorBusinessCentralWrapperTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorWrapper.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/main/java/org/drools/workbench/screens/scenariosimulation/kogito/client/editor/ScenarioSimulationEditorKogitoWrapper.java
For more details see: https://issues.redhat.com/browse/DROOLS-5104
=> DROOLS-5104: Compute scenario simulation tabs indexes dynamically

pom.xml
The jacoco.exec files are expected in target folder of particular modules. However they were produced one level upper.
This change of configuration aligns to what we use in https://github.com/kiegroup/kie-wb-common/blob/master/pom.xml
For more details see https://issues.redhat.com/browse/DROOLS-5134
=> DROOLS-5134: Update run-code-coverage profile

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/pom.xml, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-marshaller/pom.xml
We use set of librares for xsd -> java -> js conversion.
Such conversion is is needed in DMN and Scenario Simalation marshaling modules to be able run editors without application server.
This PR unify the versions of used libraries.
For more details see https://issues.redhat.com/browse/DROOLS-5057
Ensemble with:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1212
- https://github.com/kiegroup/kie-wb-common/pull/3209
=> DROOLS-5057: Unify xsd -> java -> js conversion

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime/pom.xml
For more details see https://issues.redhat.com/browse/DROOLS-5171
=> DROOLS-5171 Remove unused dependencies

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/main/java/org/drools/workbench/screens/scenariosimulation/kogito/client/dmn/AbstractKogitoDMNService.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/main/java/org/drools/workbench/screens/scenariosimulation/kogito/client/dmn/ClientDMNType.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/test/java/org/drools/workbench/screens/scenariosimulation/kogito/client/dmn/AbstractKogitoDMNServiceTest.java
It may be a little time expensive to test before [this other PR](https://github.com/kiegroup/drools-wb/pull/1333) get merged. You can cherry-pick the commit from this PR in [this branch](https://github.com/yesamer/drools-wb/tree/DROOLS-5038) if you want and use the scesim testing webapp.
The idea behind this change is:
1. Create all the DMN types in a recursive way ignoring its fields
2. Resolve the DMN types fields
Using this approach you solve [the issue reported in the JIRA](https://issues.redhat.com/browse/KOGITO-1566) and also the following situation:
tPerson [structure]
-name[string]
-address[tAdress]
tAddress[structure]
-street[String]
-country[tCountry]
tCountry
-name[String]
-president[tPerson]
Notice that tPerson has a tAddress which have a tCountry which have a tPerson and so …
=> KOGITO-1566: [SCESIM Editor] DMN Type with nested objects doesn’t works correctly

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/pages/FieldPage.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/wizard/column/pages/FieldPageTest.java
The issue is in FieldPage#setupListFieldView method. It is invoked twice. Unfortunately was not able to investigate why.
The issue is it clears the field select box immediately when invoked and do not wait for new fields are loaded.
So basically when setupListFieldView is invoked it clears select box of fields, however first load/callback was not finished that time.
For more details see: https://issues.redhat.com/browse/DROOLS-5255
=> DROOLS-5255: Wait with field page setup until model is loaded

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime/pom.xml, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime/src/main/java/org/drools/workbench/screens/scenariosimulation/webapp/client/dropdown/ScenarioSimulationKogitoRuntimeCreationAssetsDropdownProviderImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime/src/test/java/org/drools/workbench/screens/scenariosimulation/webapp/client/dropdown/ScenarioSimulationKogitoRuntimeCreationAssetsDropdownProviderImplTest.java
@danielezonca @dupliaka Can you please test and review it?
Added a filter which discard all dmn files inside a `target/` path (and subfolder level).
https://issues.redhat.com/browse/KOGITO-2000
=> KOGITO-2000: Filter DMN files inside target/ directory

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/util/DMNSimulationSettingsCreationStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/util/DMNSimulationSettingsCreationStrategyTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/main/java/org/drools/workbench/screens/scenariosimulation/kogito/client/dmn/KogitoScenarioSimulationBuilder.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/test/java/org/drools/workbench/screens/scenariosimulation/kogito/client/dmn/KogitoScenarioSimulationBuilderTest.java
@danielezonca @dupliaka Can you please review and test?
Basically, the label  of nested properties was wrong in the case of multiple nested element. 
This is because, multiple nested properties shared the same list used to determine the label and the `expressionElement` list. 
To solve the issue, I simply created a new list of previous step for any nested property.
The fix is applied for both KOGITO and BC. Considering they are not sharing this part of code (in BC is on server side), the fix is applied in 2 different points
https://issues.redhat.com/browse/DROOLS-5250
=> DROOLS-5250 (ex KOGITO-1685): Wrong label name for multiple nested elements

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/main/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/rightpanel/coverage/CoverageElementViewImpl.html, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/resources/org/drools/workbench/screens/scenariosimulation/client/resources/css/ScenarioSimulationEditorStyles.css
@danielezonca @dupliaka Can you please test and review it?
Added word-wrap: break-word; property to inherited css rule .kie-coverage__dl-horizontal dt
https://issues.redhat.com/browse/DROOLS-5308
https://issues.redhat.com/browse/RHPAM-2925
=> DROOLS-5308: Not able to read number of times rule fire in Scenario Coverage Report if rule name is longer than 27 characters

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/main/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/editor/ScenarioSimulationEditorBusinessCentralWrapper.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorWrapper.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/main/java/org/drools/workbench/screens/scenariosimulation/kogito/client/editor/ScenarioSimulationEditorKogitoWrapper.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/test/java/org/drools/workbench/screens/scenariosimulation/kogito/client/editor/ScenarioSimulationEditorKogitoWrapperTest.java
@danielezonca @dupliaka can you please review and test it?
I noticed that `columnWidth` changes were not saved in VSCode Kogito Editor. Scope of this PR is to let this mechanism works.
`wrappedSave` method was removed because not called anywhere.
https://issues.redhat.com/browse/KOGITO-2189
=> KOGITO-2189: Columns widths are not correctly saved in Scesim Editor KOGITO

drools-wb-screens/drools-wb-drl-text-editor/drools-wb-drl-text-editor-backend/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider, drools-wb-screens/drools-wb-dsl-text-editor/drools-wb-dsl-text-editor-backend/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider, drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-backend/src/test/java/org/drools/workbench/screens/dtablexls/backend/server/DecisionTableXLSServiceImplTest.java, drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-backend/src/test/java/org/drools/workbench/screens/dtablexls/backend/server/conversion/DecisionTableXLSToDecisionTableGuidedConverterTest.java, drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-backend/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider, drools-wb-screens/drools-wb-enum-editor/drools-wb-enum-editor-backend/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider, drools-wb-screens/drools-wb-globals-editor/drools-wb-globals-editor-backend/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/src/test/java/org/drools/workbench/screens/guided/dtable/backend/server/GuidedDecisionTableEditorGraphDeleteHelperTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/src/test/java/org/drools/workbench/screens/guided/dtable/backend/server/GuidedDecisionTableEditorGraphRenameHelperTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/src/test/java/org/drools/workbench/screens/guided/dtable/backend/server/GuidedDecisionTableEditorServiceImplTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/src/test/java/org/drools/workbench/screens/guided/dtable/backend/server/GuidedDecisionTableGraphEditorServiceImplTest.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-backend/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider, drools-wb-screens/drools-wb-guided-dtree-editor/drools-wb-guided-dtree-editor-backend/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-backend/src/test/java/org/drools/workbench/screens/guided/rule/backend/server/GuidedRuleEditorCopyHelperTest.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-backend/src/test/java/org/drools/workbench/screens/guided/rule/backend/server/GuidedRuleEditorRenameHelperTest.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-backend/src/test/java/org/drools/workbench/screens/guided/rule/backend/server/GuidedRuleEditorServiceImplTest.java, drools-wb-screens/drools-wb-guided-rule-editor/drools-wb-guided-rule-editor-backend/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider, drools-wb-screens/drools-wb-guided-scorecard-editor/drools-wb-guided-scorecard-editor-backend/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider, drools-wb-screens/drools-wb-guided-template-editor/drools-wb-guided-template-editor-backend/src/test/java/org/drools/workbench/screens/guided/template/server/GuidedRuleTemplateEditorServiceImplTest.java, drools-wb-screens/drools-wb-guided-template-editor/drools-wb-guided-template-editor-backend/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider, drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-backend/src/test/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider
* Disable JGit specific features when JGit is not the default FS
* Add a switch to choose between Monitoring and Simplified Monitoring
Simplified monitoring is the K8S FS based solution. This can't use JGit specific parts so they are disabled (Like _Pages_)
Possible values:
* -Dorg.appformer.server.simplified.monitoring.enabled=true/false
* https://github.com/kiegroup/appformer/pull/882
* https://github.com/kiegroup/kie-wb-common/pull/3128
* https://github.com/kiegroup/drools-wb/pull/1363
* https://github.com/kiegroup/jbpm-designer/pull/881
=> AF-2410: default:// as main file system

drools-wb-screens/drools-wb-guided-template-editor/drools-wb-guided-template-editor-client/src/main/java/org/drools/workbench/screens/guided/template/client/editor/TemplateDataCellFactory.java, drools-wb-screens/drools-wb-guided-template-editor/drools-wb-guided-template-editor-client/src/test/java/org/drools/workbench/screens/guided/template/client/editor/TemplateDataCellFactoryTest.java
Users were not able to select multiple numbers for 'in', 'not in' operators on the guided rule template 'Data' tab.
For more details see: https://issues.redhat.com/browse/DROOLS-5327
=> DROOLS-5327: Fix guided rule template multiselect dropdown for numbers

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/CollectionViewImpl.html, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/CollectionViewImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/CollectionViewImplTest.java
@dupliaka @danielezonca Can you please test and review?
To solve the issue I added a backdrop behind the modal, in this way it's not possible to interact with the rest of the page. 
I applied some changes on the collection editor buttons as well, changing their order and adding icons. 
The result:
https://issues.redhat.com/browse/DROOLS-4995
=> DROOLS-4995: Error popups when collection editor dialog is open

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/util/DMNUtils.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/util/DMNUtilsTest.java
@danielezonca @dupliaka Can you please review and test it?
Regression bug introduced with https://github.com/kiegroup/drools-wb/pull/1364 
(Fix for 
- https://issues.redhat.com/browse/DROOLS-5317
- https://issues.redhat.com/browse/RHDM-1153)
Basically, in case of a `isCollection()` DMNType, the previous behavior was correct (i.e. the correct name the validate is `DMNType.name`), because the `FactMapping.genericType` refers to `DMNType.getName` and not to `DMNType.getBaseType().getName()`
Therefore, in case of `isCollection() == true`, `DMNType.getName` is returned (as code did previously)
=> DROOLS-5364: Test scenario reports data type change during creation

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/main/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenter.java, drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/widget/table/GuidedDecisionTablePresenterTest.java
See https://issues.redhat.com/browse/RHPAM-2992
Before
After:
=> RHPAM-2992: Not able to lock guide decision table asset in business-central

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-api/src/main/java/org/drools/workbench/screens/scenariosimulation/model/typedescriptor/FactModelTree.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-api/src/test/java/org/drools/workbench/screens/scenariosimulation/model/typedescriptor/PropertyTypeNameTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/DMNTypeServiceImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/util/DMNSimulationSettingsCreationStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/AbstractDMNTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/DMNTypeServiceImplTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/util/DMNSimulationSettingsCreationStrategyTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/test/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/editor/strategies/BusinessCentralDMODataManagementStrategyTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/AbstractDMODataManagementStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/AbstractDataManagementStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/factories/CollectionEditorSingletonDOMElementFactory.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/FieldItemPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/FieldItemView.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/FieldItemViewImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/ListGroupItemPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/TestProperties.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/actualcommands/SetHeaderCellValueCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/AbstractDMODataManagementStrategyTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/AbstractDataManagementStrategyTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/factories/CollectionEditorSingletonDOMElementFactoryTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/AbstractTestToolsTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/FieldItemPresenterTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/FieldItemViewTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/ListGroupItemPresenterTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/TestToolsPresenterTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/main/java/org/drools/workbench/screens/scenariosimulation/kogito/client/dmn/AbstractKogitoDMNService.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/main/java/org/drools/workbench/screens/scenariosimulation/kogito/client/dmn/KogitoScenarioSimulationBuilder.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/test/java/org/drools/workbench/screens/scenariosimulation/kogito/client/dmn/AbstractKogitoDMNServiceTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/test/java/org/drools/workbench/screens/scenariosimulation/kogito/client/dmn/KogitoScenarioSimulationBuilderTest.java
@danielezonca @jstastny-cz 
Backport of https://github.com/kiegroup/drools-wb/pull/1397 (Cherrypicked, not other changes) in `7.39.x` branch 
https://issues.redhat.com/browse/DROOLS-5317
https://issues.redhat.com/browse/RHDM-1153
=> [7.39.x] DROOLS-5317: Scenario Simulation shows misleading data type if DMN applies a constraint 

drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-backend/src/main/java/org/drools/workbench/screens/dtablexls/backend/server/DecisionTableXLSServiceImpl.java, drools-wb-screens/drools-wb-dtable-xls-editor/drools-wb-dtable-xls-editor-backend/src/test/java/org/drools/workbench/screens/dtablexls/backend/server/DecisionTableXLSServiceImplTest.java
https://issues.redhat.com/browse/DROOLS-5457
(cherry picked from commit b8e8061d3c3a933863b0b404e5ee4f215db43d1b)
=> [7.39.x] DROOLS-5457 : XLS Decision table: File indexed before content is saved

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/domelements/ScenarioHeaderTextAreaDOMElement.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/domelements/ScenarioHeaderTextAreaDOMElementTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/factories/AbstractFactoriesTest.java
The issue was intorduced by fixing scrolling when edit mode was active (DROOLS-4584).
The current state cancel edit mode when scrolling occurs.
For more details see:
- https://issues.redhat.com/browse/DROOLS-5576
- https://issues.redhat.com/browse/DROOLS-4584
[link](https://www.example.com)
paste the link(s) from GitHub here
**How to retest or run**:
* a pull request please add comment: regex **[.\*[j|J]enkins,?.\*(retest|test) this.\*]**
* a full downstream build please add comment: regex **[.*\[j|J]enkins,?.\*(execute|run|trigger|start|do) fdb.\*]**
* a compile downstream build please  add …
=> DROOLS-5576: Cancel editing mode properly for header cells

.github/workflows/pull_request.yml
<pre>
How to retest a PR or trigger a specific build:
</pre>
=> ulimit removed from drools-wb upstream command

drools-wb-webapp/.gitignore, drools-wb-webapp/pom.xml, drools-wb-webapp/src/main/resources/org/drools/workbench/DroolsWorkbench.gwt.xml, drools-wb-webapp/src/main/webapp/drools-wb.html
**JIRA**: [KOGITO-2664](https://issues.redhat.com/browse/KOGITO-2664): [DMN Designer] Multiple DRDs support
**Part of an ensemble**:
- https://github.com/kiegroup/kie-wb-common/pull/3379
- https://github.com/kiegroup/drools-wb/pull/1416
- https://github.com/kiegroup/kie-wb-distributions/pull/1054
- **Business Central**: [WAR file v6](https://www.dropbox.com/s/6lovcz78ixv7a55/business-central-v6.war?dl=0)
- **VS Code**: [plugin v6](https://www.dropbox.com/s/ukfin8xsp5rl5sj/plugin-v6.vsix?dl=0)
This PR covers the following JIRAs:
- [KOGITO-2665](https://issues.redhat.com/browse/KOGITO-2665): Marshaller - Adopt the first DMNDiagram as the DRG (author: @karreiro)
- [KOGITO-2965](https://issues.redhat.com/browse/KOGITO-2965): Graph - Palette changes (author: @danielzhe)
- …
=> KOGITO-2664: [DMN Designer] Multiple DRDs support

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime/src/main/java/org/drools/workbench/screens/scenariosimulation/webapp/client/dropdown/ScenarioSimulationKogitoRuntimeCreationAssetsDropdownProviderImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-runtime/src/test/java/org/drools/workbench/screens/scenariosimulation/webapp/client/dropdown/ScenarioSimulationKogitoRuntimeCreationAssetsDropdownProviderImplTest.java
I received some requests to modify the current pattern used to search DMN files. Currently it retrieves all DMN file under `src/**` glob, which is too strict in some cases (It's required to open VS with `src` as a root directory. 
Our requirement is to hide all duplicated DMN files on `target/` directory, so I decided to retrieve all DMN files from VSCode and apply a filter which follow that logic.
**JIRA**: https://issues.redhat.com/browse/KOGITO-3302
<details>
<summary>
</summary>
* <b>a full production downstream …
=> KOGITO-3302: Filtering out all DMNs inside target directory.

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/main/java/org/drools/workbench/screens/scenariosimulation/kogito/client/popup/ScenarioSimulationKogitoCreationPopupView.html, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/main/java/org/drools/workbench/screens/scenariosimulation/kogito/client/popup/ScenarioSimulationKogitoCreationPopupView.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/test/java/org/drools/workbench/screens/scenariosimulation/kogito/client/popup/ScenarioSimulationKogitoCreationPopupViewTest.java
Aim of this PR is to enhance  Test Scenario creation User Experience in Kogito (VSCode). 
Improved features are:
- Currently is possible for the user to close the creation popup. Closing it, the user will land in a dead state, where is not possible to apply any action ( only closing and opening again the file). For this reason, I removed closing buttons. 
- "Create Button" enablement. Currently if the user select a DMN file from the dropdown and then select "Select" item in the dropdown, the button remains enabled. Clicking on it will lead to an error. With this PR the button will be disabled in such a case.
**JIRA**: https://issues.redhat.com/browse/KOGITO-4122
[link](https://www.example.com)
<details>
<summary>
</summary>
* <b>a pull …
=> KOGITO-4122: Improve Test Scenario creation UX

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/pom.xml, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/main/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/editor/ScenarioSimulationEditorBusinessCentralWrapper.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/test/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/editor/ScenarioSimulationEditorBusinessCentralWrapperTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/ScenarioSimulationEventHandler.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorWrapper.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/ScenarioSimulationEventHandlerTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorPresenterTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/main/java/org/drools/workbench/screens/scenariosimulation/kogito/client/editor/ScenarioSimulationEditorKogitoWrapper.java
A cleanup of "TestResults" Alerts is now performed when:
- A Test Scenario run is launched;
- Setting data are changed;
- Test Scenario editor is closed;
**JIRA**: https://issues.redhat.com/browse/DROOLS-5122
<details>
<summary>
</summary>
</details>
=> DROOLS-5122: Test Scenario is not clearing alert 

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/main/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/editor/ScenarioSimulationEditorBusinessCentralWrapper.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/test/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/editor/ScenarioSimulationEditorBusinessCentralWrapperTest.java
The issue occurs when a new Test Scenario is created in BC and the user closes it right after its creation. In this case, the Unsaved changes modal appears even if no changes are applied by the user.
**JIRA**: https://issues.redhat.com/browse/DROOLS-5512
<details>
<summary>
</summary>
</details>
=> DROOLS-5512: Unsaved changes dialog for a Test Scenario executed right after creation

drools-wb-screens/drools-wb-guided-dtable-editor/drools-wb-guided-dtable-editor-client/src/test/java/org/drools/workbench/screens/guided/dtable/client/wizard/table/pages/FactPatternConstraintsPageTest.java
Guided decision table and guided rule editor will ofer 'contains' operator also for string fields
For more details see https://issues.redhat.com/browse/DROOLS-5883
**JIRA**: [DROOLS-5883](https://issues.redhat.com/browse/DROOLS-5883)
* https://github.com/kiegroup/kie-soup/pull/165
* kiegroup/drools#3281
<details>
<summary>
</summary>
* <b>a full production downstream …
=> DROOLS-5883: Allow contains operator for string fields

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/ElementView.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/ElementViewImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/ItemElementPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/PropertyPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/AbstractCollectionEditorTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/ElementViewImplTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/ItemElementPresenterTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/ItemElementViewImplTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/KeyValueElementViewImplTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/PropertyPresenterTest.java
The issue occurs when a "user defined" java class is used as type parameter of a List eg. `List<Clazz>` and that class contains a field which is a "user defined" java class as well. Screenshot show an example:
Author
+ books (List<Book>)
. isAvailable (boolean)
. name (string) 
. ....
+ **author (Author)**    _<----  Issue occurs with this nested class field_
. name
. ...
With current version there are several issues:
- Not possible to correctly delete / modify a list item 
- the nested **author (Author)** reference is THE SAME for all items (eg. try to create multiple items of the list. If you try to change a field of Author, this will be propagated to all items!)
**JIRA**: https://issues.redhat.com/browse/DROOLS-5230
<details>
<summary> …
=> DROOLS-5230: Managing a List of structures in Test Scenario editor produces an Exception

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-api/src/main/java/org/drools/workbench/screens/scenariosimulation/model/DMNMetadata.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-api/src/main/java/org/drools/workbench/screens/scenariosimulation/service/DMNTypeService.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/DMNTypeServiceImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/DMNTypeServiceImplTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/main/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/editor/ScenarioSimulationEditorBusinessCentralWrapper.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/main/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/editor/strategies/BusinessCentralDMNDataManagementStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/main/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/handlers/ScenarioSimulationBusinessCentralDocksHandler.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/test/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/editor/ScenarioSimulationEditorBusinessCentralWrapperTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/test/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/editor/strategies/BusinessCentralDMNDataManagementStrategyTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/test/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/handlers/ScenarioSimulationBusinessCentralDocksHandlerTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/ScenarioSimulationEventHandler.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/actualcommands/UpdateSettingsDataCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorWrapper.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/AbstractDMNDataManagementStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/events/UpdateSettingsDataEvent.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/handlers/AbstractScenarioSimulationDocksHandler.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/rightpanel/SettingsPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/actualcommands/UpdateSettingsDataCommandTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/ScenarioSimulationEditorPresenterTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/AbstractDMNDataManagementStrategyTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/handlers/AbstractScenarioSimulationDocksHandlerTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/main/java/org/drools/workbench/screens/scenariosimulation/kogito/client/editor/ScenarioSimulationEditorKogitoWrapper.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/main/java/org/drools/workbench/screens/scenariosimulation/kogito/client/editor/strategies/KogitoDMNDataManagementStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/test/java/org/drools/workbench/screens/scenariosimulation/kogito/client/editor/ScenarioSimulationEditorKogitoWrapperTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-kogito-client/src/test/java/org/drools/workbench/screens/scenariosimulation/kogito/client/editor/strategies/KogitoDMNDataManagementStrategyTest.java
Changes introduced in this PR:
- When changing DMN reference in the Setting dock, DMN Name and DMN Namespace are now updated (BC and Kogito);
- When changing DMN reference in the Setting dock, the Fact list in the Test Tools dock is now updated (BC and Kogito);
- When changing DMN reference in the Setting dock a Validation is performed (BC only);
**JIRA**: https://issues.redhat.com/browse/DROOLS-4986
<details>
<summary>
</summary>
* <b>a full production downstream build</b> please add comment: <b>Jenkins execute …
=> DROOLS-4986: Change dmn model does not update model name and namespace

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/ElementView.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/ElementViewImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/ItemElementPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/PropertyPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/AbstractCollectionEditorTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/ElementViewImplTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/ItemElementPresenterTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/ItemElementViewImplTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/KeyValueElementViewImplTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/collectioneditor/PropertyPresenterTest.java
Backport of https://github.com/kiegroup/drools-wb/pull/1455
The issue occurs when a "user defined" java class is used as type parameter of a List eg. `List<Clazz>` and that class contains a field which is a "user defined" java class as well. Screenshot show an example:
Author
+ books (List<Book>)
. isAvailable (boolean)
. name (string) 
. ....
+ **author (Author)**    _<----  Issue occurs with this nested class field_
. name
. ...
With current version there are several issues:
- Not possible to correctly delete / modify a list item 
- the nested **author (Author)** reference is THE SAME for all items (eg. try to create multiple items of the list. If you try to change a field of Author, this will be propagated to all items!)
**JIRA**: https://issues.redhat.com/browse/DROOLS-5230
<details> …
=> [7.48.x] DROOLS-5230: Managing a List of structures in Test Scenario editor produces an Exception

drools-wb-webapp/pom.xml
**JIRA**: [KOGITO-4919](https://issues.redhat.com/browse/KOGITO-4919): [DMN Designer] SDM is broken on -kogito-webapp-runtime
--
**Part of an ensemble:**
- https://github.com/kiegroup/kie-wb-common/pull/3611
- https://github.com/kiegroup/drools-wb/pull/1484
- https://github.com/kiegroup/kie-wb-distributions/pull/1097
--
<details>
<summary>
</summary>
* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>
=> KOGITO-4919: [DMN Designer] SDM is broken on -kogito-webapp-runtime

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/main/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/rightpanel/coverage/CoverageReportDonutPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/main/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/rightpanel/coverage/CoverageReportPresenter.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-businesscentral-client/src/test/java/org/drools/workbench/screens/scenariosimulation/businesscentral/client/rightpanel/coverage/CoverageReportPresenterTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/utils/ConstantHolder.java
This PR modifies Doughnut chart tooltip in order to be fixed (sticky), avoiding the reported issue (see JIRA)
**JIRA**: https://issues.redhat.com/browse/DROOLS-4863
[link](https://drive.google.com/file/d/1t5VfpXcUdJsqun465OMF3tMErjY582Rr/view?usp=sharing)
<details>
<summary>
</summary>
</details>
=> DROOLS-4863: Doughnut chart tooltip doesn't show correctly at Coverage Report panel 

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-api/src/main/java/org/drools/workbench/screens/scenariosimulation/model/typedescriptor/FactModelTree.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-api/src/test/java/org/drools/workbench/screens/scenariosimulation/model/typedescriptor/FactModelTreeTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/actualcommands/AbstractSelectedColumnCommand.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/AbstractDMODataManagementStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/editor/strategies/DataManagementStrategy.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/factories/CollectionEditorSingletonDOMElementFactory.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/models/AbstractScesimGridModel.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/models/BackgroundGridModel.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/models/ScenarioGridModel.java
**JIRA**: https://issues.redhat.com/browse/DROOLS-6477
* https://github.com/kiegroup/drools/pull/3725
The issue occurs when the user imports a Collection or a Map from the "Data Object" tab.
In the  Test Tools area, the Collection (eg. ArrayList) will wrongly show `empty` as a field. Selecting it or the `ArrayList`fact, will not enable the Guided Collection Editor as expected. 
With the change introduced with this PR, now `value` field will be shown. As a results, adding the value parameter in the grid, will  show the Guided Collection Editor.
<details>
<summary>
</summary>
* <b>a full downstream build</b> please add comment: <b>Jenkins …
=> DROOLS-6477: Collections Data Objects can be filled with expressions only.

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/commands/ScenarioSimulationEventHandler.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/main/java/org/drools/workbench/screens/scenariosimulation/client/models/AbstractScesimGridModel.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/commands/ScenarioSimulationEventHandlerTest.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-client/src/test/java/org/drools/workbench/screens/scenariosimulation/client/models/AbstractScesimGridModelTest.java
**JIRA**: https://issues.redhat.com/browse/DROOLS-6494
@jomarko This PR fixes the 2^ issue you found here https://github.com/kiegroup/drools-wb/pull/1503#pullrequestreview-703931429 . Considering you found it, I assign the QE review to you, but please feel free to reassign.
Step to reproduce: 
- Create a new Test Scenario (RULE)
- Form "Data Object" tab, add any Java class available. (eg. Integer)
- Add the Integer > value property in the grid
- Try to re-assign the same column to an expression, selecting "Integer" class in the Test Tools.
- Nothing happens
- (the same occurs if you assign the expression first and then reassign it with Integer > value.
P.S. This PR requires https://github.com/kiegroup/drools-wb/pull/1503 to be merged first, because it relies on its changes.
<details> …
=> DROOLS-6494: No effects when assigning a not-expression Simple Type column to expression type (and viceversa) 

drools-wb-webapp/pom.xml
This PR partially reverts https://github.com/kiegroup/drools-wb/commit/79c74bb5c27f27b11c34a9991489eded5a9ce090, which broke Super DEV Mode for drools-wb-webapp.
<details>
<summary>
</summary>
</details>
=> AF-2889 Partially reverted: It brakes GWT Super Dev Mode

drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-backend/src/test/java/org/drools/workbench/screens/testscenario/backend/server/ScenarioRunnerServiceTest.java
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can …
=> fixing an unstable test

drools-wb-screens/drools-wb-test-scenario-editor/drools-wb-test-scenario-editor-backend/src/test/java/org/drools/workbench/screens/testscenario/backend/server/ScenarioRunnerServiceTest.java
backporting https://github.com/kiegroup/drools-wb/pull/1532
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send …
=> [7.59.x] Backport ignored test for ScenarioRunnerServiceTest.testIsGithubContributor

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/ScenarioSimulationServiceImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/ScenarioSimulationServiceImplTest.java
**JIRA**: https://issues.redhat.com/browse/DROOLS-6905
When a scesim assets is added in the project, the `drools-decisiontable` will be automatically added in the project related pom.xml file.
This is required in case the user has XML decision table assets in its projects.
<details>
<summary>
</summary>
[build-chain …
=> DROOLS-6905: Added drools-decisiontables as dependency to compile xml decision tables assets

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/ScenarioSimulationServiceImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/ScenarioSimulationServiceImplTest.java
Backport of https://github.com/kiegroup/drools-wb/pull/1542
JIRA: https://issues.redhat.com/browse/DROOLS-6905
When a scesim assets is added in the project, the drools-decisiontable will be automatically added in the project related pom.xml file.
This is required in case the user has XML decision table assets in its projects.
=> [7.67.x-blue] DROOLS-6905: Added `drools-decisiontables` as dependency to compile xml decision tables assets

drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/main/java/org/drools/workbench/screens/scenariosimulation/backend/server/ScenarioSimulationServiceImpl.java, drools-wb-screens/drools-wb-scenario-simulation-editor/drools-wb-scenario-simulation-editor-backend/src/test/java/org/drools/workbench/screens/scenariosimulation/backend/server/ScenarioSimulationServiceImplTest.java
Backport of https://github.com/kiegroup/drools-wb/pull/1542
JIRA: https://issues.redhat.com/browse/DROOLS-6905
When a scesim assets is added in the project, the drools-decisiontable will be automatically added in the project related pom.xml file.
This is required in case the user has XML decision table assets in its projects.
=> [7.67.x] DROOLS-6905: Added `drools-decisiontables` as dependency to compile xml decision tables assets

drools-wb-webapp/pom.xml
https://issues.redhat.com/browse/BXMSPROD-1845
Related PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2097
* https://github.com/kiegroup/appformer/pull/1312
* https://github.com/kiegroup/kie-wb-common/pull/3781
* https://github.com/kiegroup/drools-wb/pull/1558
* https://github.com/kiegroup/jbpm-wb/pull/1572
* https://github.com/kiegroup/optaplanner-wb/pull/413
* https://github.com/kiegroup/kie-wb-distributions/pull/1196
=> [BXMSPROD-1845] elasticsearch removed from appformer
